# VS code cũng đẹp mà
Tui yêu cái đẹp, thấy cái gì đẹp là tui lưu lại hết à
Tui muốn sản phẩm mk làm ra có sự chỉnh chu, áp dụng được vào thực tiễn, thực sự có ích cho đời

In [1]:
import random

# https://www.fileformat.info/info/unicode/category/So/list.htm

list = ['''Dừa lòng :)) \U0001F965''',
        '\U0001F335 \U0001F335 \U0001F335',
        'Tóc giả giả \U0001FAAD',
        '9094 -> Mồm\U0001F415 vó\U0001F434',
        'Kay \U0001F332 \U0001F333 \U0001F99D \U0001F423',
        'Tăng Phúc \U0001F9A6',
        '2 Neko \U0001F451 \U0001F40D \U0001F63A \U0001F638 \U0001F639 \U0001F640',
        'Nui \U0001F35C',
        'ST \U0001F43A \U0001F427', 
        '\U0001F33B', '\U0001F337', '\U0001F338', '\U0001F339', '\U0001F33A', '\U0001F33C', '\U0001F33E', '\U0001F340']
# print(*list, sep='\n')

random_item = (random.choice(list) + ' \u2740 '+ random.choice(list) + ' \u2740 '+random.choice(list) + ' \u2740 ' + '\n')*5
print(random_item)

2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ 🌹 ❀ Tăng Phúc 🦦 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ 🌹 ❀ Tăng Phúc 🦦 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ 🌹 ❀ Tăng Phúc 🦦 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ 🌹 ❀ Tăng Phúc 🦦 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ 🌹 ❀ Tăng Phúc 🦦 ❀

In [2]:
# import libraries 

import numpy as np
import pandas as pd

#Vẽ biểu đồ
import matplotlib.pyplot as plt 

# Vẽ biểu đồ nhiệt
import seaborn as sns

from collections import Counter

In [3]:
# review file data
filename = r"E:\Chuyển từ download sang\A Học tập Bách Khoa\ĐA2\Đồ án 2 _ 2025\Project_full\Crawl_job\Data_raw\data_topcv.csv"

df=pd.read_csv(filename)
df

,index,job_link,keyword,title,company_name,location,salary,date_posted,deadline_date,company_field,job_type,job_level,experience,education,hire_number,job_expertise,description,requirements,benefits
0,1,https://www.topcv.vn/viec-lam/chuyen-vien-du-a...,Data Analyst,Chuyên Viên Dự Án Lưu Trữ & Số Hóa Tài Liệu,Viện Nghiên cứu Quản Lý Hành Chính,Hồ Chí Minh,Từ 15 triệu,2026-04-13,13/05/2026,Giáo dục / Đào tạo,Toàn thời gian,Nhân viên,Không yêu cầu,Trung cấp trở lên,10 người,"Phân tích dữ liệu, Nhân sự","Thực hiện chỉnh lý, sắp xếp, phân loại tài liệ...",Tốt nghiệp từ Trung cấp trở lên (ưu tiên các n...,Thời gian thử việc và đào tạo: 03 tháng (được ...
1,2,https://www.topcv.vn/viec-lam/da-de-data-analy...,Data Analyst,DA/DE - Data Analyst / Data Engineer Thu Nhập ...,Công ty TNHH thương mại và XNK Winki Group,Hà Nội,18 - 25 triệu,2026-04-11,30/06/2026,Bán lẻ - Hàng tiêu dùng - FMCG,Toàn thời gian,Nhân viên,1 năm,Cao Đẳng trở lên,2 người,"Data Analyst, IT - Phần mềm, Thương mại điện t...",Thu thập & Xây dựng luồng dữ liệu (ETL / Data ...,Kinh nghiệm: 1 3 năm ở vị trí Data Analyst. Bắ...,Thu nhập: Lương cơ bản 15.000.000 25.000.000 V...
2,3,https://www.topcv.vn/viec-lam/business-analyst...,Data Analyst,Business Analyst ( BA - Chuyên Viên Phân Tích ...,Công ty TNHH thương mại và XNK Winki Group,Hà Nội,18 - 25 triệu,2026-04-11,30/06/2026,Bán lẻ - Hàng tiêu dùng - FMCG,Toàn thời gian,Nhân viên,1 năm,Cao Đẳng trở lên,2 người,"Data Analyst, Thương mại điện tử, IT - Phần mề...",Khảo sát & Phân tích nghiệp vụ (Requirement Ga...,Kinh nghiệm: Có từ 1 năm kinh nghiệm làm Busin...,"Thu nhập cốt lõi: Dải lương cơ bản 18,000,000 ..."
3,4,https://www.topcv.vn/viec-lam/chuyen-vien-phan...,Data Analyst,Chuyên Viên Phân Tích Dữ Liệu & AI Agent,Công ty Cổ phần Thương mại Dịch vụ 4B,Hồ Chí Minh,Thoả thuận,2026-04-08,08/05/2026,Dược phẩm / Y tế / Công nghệ sinh học,Toàn thời gian,Nhân viên,2 năm,Cao Đẳng trở lên,1 người,"Data Analyst, Chăm sóc sức khỏe / Làm đẹp, Y t...",Hệ thống Dữ liệu & Tự động hóa (40%) Kết nối đ...,"Hiểu biết sâu về cấu trúc dữ liệu, kho dữ liệu...",Thu nhập: Mức lương cạnh tranh theo năng lực (...
4,5,https://www.topcv.vn/viec-lam/product-builder-...,Data Analyst,Product Builder (Remote),CÔNG TY CỔ PHẦN KIMQ,Hồ Chí Minh,Thoả thuận,2026-04-07,07/05/2026,IT - Phần mềm,Toàn thời gian,Nhân viên,2 năm,Đại Học trở lên,2 người,Data Analyst,Trực tiếp xây dựng và phát triển sản phẩm bằng...,Có kinh nghiệm xây dựng sản phẩm bằng công cụ ...,Lương: thỏa thuận theo năng lực ứng viên Được ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,749,https://www.topcv.vn/brand/misa/tuyen-dung/chu...,AI Engineer,Chuyên Viên Kinh Doanh Giải Pháp AI Cho Doanh ...,Công ty Cổ phần MISA,Hà Nội,NaN,2026-06-02,09/07/2026,NaN,NaN,NaN,NaN,NaN,NaN,"Kinh doanh phần mềm, Tài chính, Ngân hàng, Kế ...","Tập đoàn MISA, thành lập năm 1994, là doanh ng...",Độ tuổi: 21 27 tuổi. Tốt nghiệp Cao đẳng trở l...,1. Thu nhập và phúc lợi: Lương cứng thỏa thuận...
749,750,https://www.topcv.vn/viec-lam/ai-engineer-tu-1...,AI Engineer,"AI Engineer (Từ 1,5 Năm Kinh Nghiệm)",CÔNG TY CỔ PHẦN ĐẦU TƯ CÔNG NGHỆ VÀ THƯƠNG MẠI...,Hà Nội,Thoả thuận,2026-06-09,12/07/2026,IT - Phần mềm,Làm việc tại văn phòng / Onsite,Nhân viên,1 năm,Đại Học trở lên,1 người,"AI Engineer, IT - Phần mềm, IT - Phần cứng và ...",Softdreams đang tìm kiếm Kỹ sư LLM có kinh ngh...,"Tối thiểu 1,5 năm kinh nghiệm thực tế trong lĩ...","Mức lương: 17,000,00025,000,000 Trợ cấp ăn trư..."
750,751,https://www.topcv.vn/viec-lam/lap-trinh-vien-t...,AI Engineer,Lập Trình Viên Tự Động Hóa Và Ứng Dụng AI,Công ty TNHH Funtime Media Corp,Hải Phòng,9 - 12 triệu,2026-06-09,09/07/2026,Khác,Làm việc tại văn phòng / Onsite,Nhân viên,Dưới 1 năm,Cao Đẳng trở lên,1 người,"Software Engineer, IT - Phần mềm, Cơ khí / Tự ...","Phân tích quy trình vận hành hiện tại, phối hợ...",Bằng cấp : Ưu tiên tốt nghiệp ngành công nghệ ...,Thu nhập: 8.000.000 – 12.000.000 đồng (Lương C...
751,752,https://www.topcv.vn/viec-lam/content-creator-...,AI Engineer,Content Creator Part Time (Ứng Dụng AI),CÔNG TY CỔ PHẦN MỸ PHẨM THIÊN NHIÊN CỎ MỀM,Hà Nội,4 - 5 triệu,2026-06-09,09/07/2026,Dược phẩm / Y tế / Công nghệ sinh học,Làm việc tại văn phòng / Onsite,Thực tập sinh,Không yêu cầu,Đại Học trở lên,1 người,"Content Creator, Chăm sóc sức khỏe / Làm đẹp, ...",Lên ý tưởng và xây dựng kịch bản short video t...,Sinh viên năm 2–4 hoặc mới tốt nghiệp các ngàn...,Chế độ: Lương cứng + KPIs: Tổng thu nhập 4 – 5...
752,753,https://www.topcv.vn/viec-lam/thuc-tap-sinh-qu...,AI Engineer,Thực Tập Sinh Quay Dựng/Video Editor (Ứng Dụng...,công ty cổ phần giáo dục quốc tế ODIN,Hà Nội,2 - 4 triệu,2026-06-08,08/07/2026,Giáo dục / Đào tạo,Làm việc tại văn phòng / Onsite,Thực tập sinh,Dưới 1 năm,Cao Đẳng trở lên,2 người,"Photographer/Video Editor, Giáo dục / Đào tạo,...",Nền tảng Edtech về đào tạo ngoại ngữ (Ulaedu.c...,"Có kiến thức về video editing, quay chụp... Th...",Được làm việc tại 1 Công ty Edtech tiên phong ...

In [4]:
# Kiểm tra kiểu dữ liệu
df.dtypes

index             int64
job_link         object
keyword          object
title            object
company_name     object
location         object
salary           object
date_posted      object
deadline_date    object
company_field    object
job_type         object
job_level        object
experience       object
education        object
hire_number      object
job_expertise    object
description      object
requirements     object
benefits         object
dtype: object

In [5]:
# Thống kê các cột chứa giá trị text

# percentile list
perc = [.25, .50, .75]
  
# list of dtypes to include
include = ['object']
  
# calling describe method
desc = df.describe(percentiles=perc, include=include)
  
# display
desc

,job_link,keyword,title,company_name,location,salary,date_posted,deadline_date,company_field,job_type,job_level,experience,education,hire_number,job_expertise,description,requirements,benefits
count,753,753,753,753,750,738,753,744,661,703,738,738,738,738,753,753,753,753
unique,753,14,616,452,22,155,69,91,37,7,7,8,5,13,342,676,694,638
top,https://www.topcv.vn/viec-lam/chuyen-vien-du-a...,Data Analyst,Data Engineer,Ngân Hàng TMCP Việt Nam Thịnh Vượng (VPBank),Hà Nội,Thoả thuận,2026-04-16,30/06/2026,IT - Phần mềm,Toàn thời gian,Nhân viên,2 năm,Đại Học trở lên,1 người,"AI Engineer, IT - Phần mềm","At PREP, we are on a mission to revolutionize ...","University Degree in Computer Science, Informa...",1. Chế độ Thưởng hấp dẫn: Thưởng dịp lễ tết Th...
freq,1,265,30,19,511,356,69,48,283,602,522,200,590,522,74,6,5,9

In [6]:
# Đếm số giá trị duy nhất từng cột
df.nunique()

index            753
job_link         753
keyword           14
title            616
company_name     452
location          22
salary           155
date_posted       69
deadline_date     91
company_field     37
job_type           7
job_level          7
experience         8
education          5
hire_number       13
job_expertise    342
description      676
requirements     694
benefits         638
dtype: int64

In [7]:
# Cột Keyword có bao nhiêu giá trị duy nhất
df['keyword'].unique().tolist()

['Data Analyst',
 'Business Intelligence',
 'Data Quality Analyst',
 'Database Developer',
 'Product Analyst',
 'Data Engineer',
 'Data Scientist',
 'Machine Learning',
 'NLP Engineer',
 'Database Administrator',
 'Big Data Engineer',
 'AI Engineer',
 'ETL',
 'Data Warehouse']

In [8]:
# Cột location có bao nhiêu giá trị duy nhất
df['location'].unique().tolist()

['Hồ Chí Minh',
 'Hà Nội',
 'Bắc Ninh',
 'Đồng Nai',
 'Gia Lai',
 'Đà Nẵng',
 'Hải Phòng',
 'Hà Nội,Hồ Chí Minh',
 'Lào Caivà 31 nơi khác',
 'Hồ Chí Minh,Hà Nội',
 'Hưng Yên',
 'Hà Nội,Phú Thọ',
 'Hà Nộivà 2 nơi khác',
 'Hưng Yên , Hà Nội',
 'Hưng Yên,Hà Nội',
 'Nhật Bản',
 'An Giang',
 'Vĩnh Long',
 'Bắc Ninh , Đồng Nai',
 nan,
 'Hà Nội,Đà Nẵng',
 'Hà Nội , Hồ Chí Minh',
 'Khánh Hòa']

In [9]:
# Cột salary có bao nhiêu giá trị duy nhất
df['salary'].unique().tolist()

['Từ 15 triệu',
 '18 - 25 triệu',
 'Thoả thuận',
 '20 - 40 triệu',
 '10 - 25 triệu',
 '25 - 40 triệu',
 '8 - 9 triệu',
 '9 - 13 triệu',
 '15 - 30 triệu',
 '3 - 5 triệu',
 '12 - 16 triệu',
 '8 - 13 triệu',
 '13 - 25 triệu',
 '12 - 20 triệu',
 '1,000 - 1,500 USD',
 '14 - 17 triệu',
 '15 - 20 triệu',
 '1 - 3 triệu',
 '18 - 22 triệu',
 '14 - 18 triệu',
 '30 - 50 triệu',
 '30 - 45 triệu',
 '45 - 70 triệu',
 '8 - 16 triệu',
 '16 - 20 triệu',
 '10 - 13 triệu',
 '11 - 15 triệu',
 '8 - 10 triệu',
 '10 - 15 triệu',
 '30 - 35 triệu',
 '12 - 18 triệu',
 'Tới 3.3 triệu',
 '13 - 19 triệu',
 '2 - 3 triệu',
 'Tới 80 triệu',
 'Tới 5 triệu',
 '16 - 22 triệu',
 '35 - 50 triệu',
 'Từ 8 triệu',
 '20 - 50 triệu',
 '20 - 25 triệu',
 '6.5 - 9.5 triệu',
 'Từ 3 triệu',
 'Từ 30 triệu',
 '10 - 14 triệu',
 '20 - 30 triệu',
 '15 - 35 triệu',
 '15 - 25 triệu',
 '17 - 32 triệu',
 '8 - 11 triệu',
 '8 - 15 triệu',
 '40 - 60 triệu',
 '10 - 12 triệu',
 '10,000,000 - 12,000,000 USD',
 'Tới 20 triệu',
 '13 - 20 triệu',
 '15 - 21 triệu',
 'Tới 35 triệu',
 'Tới 26.5 triệu',
 '25 - 30 triệu',
 '25 - 32 triệu',
 '22 - 28 triệu',
 '10 - 60 triệu',
 '3.5 - 5 triệu',
 '13 - 15 triệu',
 '15 - 50 triệu',
 'Tới 60 triệu',
 'Tới 40 triệu',
 '25 - 35 triệu',
 'Tới 25 triệu',
 '13 - 18 triệu',
 'Tới 2 triệu',
 '16 - 18 triệu',
 '15 - 28 triệu',
 'Tới 45 triệu',
 '25 - 300 triệu',
 '8 - 12 triệu',
 '15 - 18 triệu',
 '10 - 20 triệu',
 '9 - 12 triệu',
 '35 - 65 triệu',
 '18 - 30 triệu',
 'Tới 4 triệu',
 '35 - 40 triệu',
 'Từ 2.5 triệu',
 '20 - 35 triệu',
 '70 - 110 triệu',
 'Tới 50 triệu',
 '8 - 30 triệu',
 '55 - 80 triệu',
 '30 - 40 triệu',
 '40 - 50 triệu',
 '25 - 28 triệu',
 '6 - 8 triệu',
 'Tới 2.1 triệu',
 '25 - 50 triệu',
 '12 - 13 triệu',
 '15 - 17 triệu',
 '15 - 22 triệu',
 '36 - 72 triệu',
 '10 - 17 triệu',
 '12 - 15 triệu',
 '7 - 40 triệu',
 'Tới 30 triệu',
 '14 - 20 triệu',
 '10 - 30 triệu',
 '14 - 15 triệu',
 'Tới 13 triệu',
 'Tới 1.5 triệu',
 '35 - 45 triệu',
 'Tới 3 triệu',
 '36 - 86 triệu',
 '20 - 27 triệu',
 '700 - 1,000 USD',
 '16 - 25 triệu',
 'Tới 2,000 USD',
 '12 - 22 triệu',
 '6 - 10 triệu',
 'Tới 100 triệu',
 '800 - 3,500 USD',
 'Tới 75 triệu',
 '0.2 - 0.2 triệu',
 '25 - 45 triệu',
 '5 - 7 triệu',
 'Tới 28 triệu',
 '17 - 24 triệu',
 '18 - 24 triệu',
 '35 - 60 triệu',
 '7 - 12 triệu',
 '6 - 12 triệu',
 'Tới 3,000 USD',
 '7 - 11 triệu',
 '10 - 18 triệu',
 '18 - 20 triệu',
 '32 - 40 triệu',
 '22 - 30 triệu',
 '10 - 11 triệu',
 '27 - 45 triệu',
 '20 - 39 triệu',
 nan,
 'Tới 27 triệu',
 '9 - 18 triệu',
 '20 - 60 triệu',
 '20 - 32 triệu',
 '18 - 28 triệu',
 '4 - 6 triệu',
 'Từ 12.5 triệu',
 '22 - 33 triệu',
 '15 - 2,147.5 triệu',
 '20 - 34 triệu',
 '5 - 10 triệu',
 '4 - 5 triệu',
 '30 - 60 triệu',
 'Từ 22 triệu',
 '20 - 28 triệu',
 '2 - 4 triệu']

In [10]:
# Cột job_type có bao nhiêu giá trị duy nhất
df['job_type'].unique().tolist()

['Toàn thời gian',
 'Bán thời gian',
 'Thực tập',
 'Khác',
 'Làm tại nhà',
 nan,
 'Làm việc tại văn phòng / Onsite',
 'Kết hợp tại văn phòng và từ xa (Hybrid)']

In [14]:
# Cột date_posted có bao nhiêu giá trị duy nhất
df['date_posted'].unique().tolist()

['2026-04-13',
 '2026-04-11',
 '2026-04-08',
 '2026-04-07',
 '2026-04-06',
 '2026-03-30',
 '2026-04-09',
 '2026-03-14',
 '2026-04-10',
 '2026-03-23',
 '2026-03-16',
 '2026-03-31',
 '2026-03-17',
 '2026-04-22',
 '2026-04-16',
 '2026-04-21',
 '2026-04-18',
 '2026-04-17',
 '2026-03-24',
 '2026-04-20',
 '2026-04-02',
 '2026-03-26',
 '2026-04-23',
 '2026-04-24',
 '2026-04-25',
 '2026-04-30',
 '2026-04-29',
 '2026-05-01',
 '2026-04-28',
 '2026-04-27',
 '2026-04-26',
 '2026-05-04',
 '2026-05-05',
 '2026-05-08',
 '2026-05-07',
 '2026-05-06',
 '2026-05-02',
 '2026-05-11',
 '2026-05-09',
 '2026-05-12',
 '2026-05-15',
 '2026-05-14',
 '2026-05-13',
 '2026-05-10',
 '2026-05-16',
 '2026-05-21',
 '2026-05-18',
 '2026-05-20',
 '2026-05-19',
 '2026-05-17',
 '2026-05-23',
 '2026-05-22']

In [15]:
# Cột deadline_date (ngày hết hạn nộp hồ sơ) có bao nhiêu giá trị duy nhất
df['deadline_date'].unique().tolist()

['13/05/2026',
 '30/06/2026',
 '08/05/2026',
 '07/05/2026',
 '30/04/2026',
 '05/05/2026',
 '03/05/2026',
 '02/05/2026',
 '01/05/2026',
 '29/04/2026',
 '09/05/2026',
 '31/05/2026',
 '23/05/2026',
 '15/05/2026',
 '10/05/2026',
 '15/06/2026',
 '16/04/2026',
 '04/05/2026',
 '28/04/2026',
 '27/04/2026',
 '26/04/2026',
 '25/04/2026',
 '23/04/2026',
 '24/04/2026',
 '22/04/2026',
 '20/04/2026',
 '19/04/2026',
 '18/04/2026',
 '17/04/2026',
 '15/04/2026',
 '06/05/2026',
 '22/05/2026',
 '16/05/2026',
 '18/05/2026',
 '17/05/2026',
 '06/06/2026',
 '30/05/2026',
 '02/06/2026',
 '21/05/2026',
 '14/05/2026',
 '20/05/2026',
 '11/05/2026',
 '31/07/2026',
 '18/06/2026',
 '30/11/2026',
 '01/06/2026',
 '24/05/2026',
 '25/05/2026',
 '29/05/2026',
 '28/05/2026',
 '26/05/2026',
 '03/06/2026',
 '04/06/2026',
 '07/06/2026',
 '05/06/2026',
 '17/06/2026',
 '09/06/2026',
 '05/07/2026',
 '10/06/2026',
 '08/06/2026',
 '12/06/2026',
 '11/06/2026',
 '14/06/2026',
 '13/06/2026',
 '20/06/2026',
 '19/06/2026',
 '16/06/2026',
 '22/06/2026',
 '21/06/2026']

In [11]:
# Cột company_field (lĩnh vực công ty) có bao nhiêu giá trị duy nhất
df['company_field'].unique().tolist()

['Giáo dục / Đào tạo',
 'Bán lẻ - Hàng tiêu dùng - FMCG',
 'Dược phẩm / Y tế / Công nghệ sinh học',
 'IT - Phần mềm',
 'Bất động sản',
 'Luật',
 'Tài chính',
 'Sản xuất',
 'Bảo hiểm',
 'Tư vấn',
 'Môi trường',
 'Logistics - Vận tải',
 'Marketing / Truyền thông / Quảng cáo',
 nan,
 'Khác',
 'Chứng khoán',
 'Du lịch',
 'Thương mại điện tử',
 'Thời trang',
 'Viễn thông',
 'Ngân hàng',
 'Kế toán / Kiểm toán',
 'Điện tử / Điện lạnh',
 'Cơ khí',
 'Agency (Marketing/Advertising)',
 'Nhà hàng / Khách sạn',
 'Giải trí',
 'Internet / Online',
 'Xây dựng',
 'IT - Phần cứng',
 'Xuất nhập khẩu',
 'In ấn / Xuất bản',
 'Thương mại tổng hợp',
 'Nhân sự',
 'Tự động hóa',
 'Năng lượng',
 'Agency (Design/Development)',
 'Thiết kế / kiến trúc']

In [12]:
# Cột job_level cấp bậc nhân viên có bao nhiêu giá trị duy nhất
df['job_level'].unique().tolist()

['Nhân viên',
 'Thực tập sinh',
 'Trưởng nhóm',
 'Quản lý / Giám sát',
 'Trưởng/Phó phòng',
 'Trưởng chi nhánh',
 'Giám đốc',
 nan]

In [13]:
# Cột experience năm kinh nghiệm có bao nhiêu giá trị duy nhất
df['experience'].unique().tolist()

['Không yêu cầu',
 '1 năm',
 '2 năm',
 '3 năm',
 'Dưới 1 năm',
 'Trên 5 năm',
 '4 năm',
 '5 năm',
 nan]

In [14]:
# Cột education trình độ học vấn có bao nhiêu giá trị duy nhất
df['education'].unique().tolist()

['Trung cấp trở lên',
 'Cao Đẳng trở lên',
 'Đại Học trở lên',
 'Cao học trở lên',
 'Trung học phổ thông (Cấp 3) trở lên',
 nan]

In [1]:
# Cột hire_number số lượng tuyển dụng có bao nhiêu giá trị duy nhất
df['hire_number'].unique().tolist()

NameError: name 'df' is not defined

In [16]:
# Cột job_expertise chuyên môn công việc có bao nhiêu giá trị duy nhất
df['job_expertise'].unique().tolist()

['Phân tích dữ liệu, Nhân sự',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Chăm sóc sức khỏe / Làm đẹp, Y tế / Dược phẩm',
 'Data Analyst',
 'Data Analyst, Tài chính',
 'Kế toán tài chính, Tài chính, Kế toán, Kiểm toán',
 'Data Analyst, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, Logistic / Vận tải, IT - Phần mềm',
 'Data Analyst, IT - Phần mềm',
 'Data Analyst, Tài chính, IT - Phần mềm, An ninh mạng',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Kế toán',
 'Business Intelligence, Marketing / Quảng cáo, Kế toán, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Analyst, Thương mại điện tử, Marketing / Quảng cáo',
 'Data Analyst, Viễn thông, Nhân sự',
 'Phân tích dữ liệu, Năng lượng / Môi trường',
 'Business Analyst (Phân tích nghiệp vụ), Tài chính, Ngân hàng, Chứng khoán',
 'Data Analyst, IT - Phần mềm, Ngân hàng',
 'Data Analyst, Logistic / Vận tải, IT - Phần mềm',
 'Data Analyst, Game',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử',
 'Data Analyst, IT - Phần mềm, Điện toán đám mây (Cloud), IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Logistic / Vận tải',
 'Phân tích dữ liệu',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Y tế / Dược phẩm',
 'Phân tích dữ liệu, Năng lượng / Môi trường, Tổ chức phi lợi nhuận',
 'Data Analyst, Công nghệ kỹ thuật, IT - Phần mềm, Game',
 'Tư vấn nhân sự',
 'Data Analyst, IT - Phần mềm, May mặc / Thời trang, Logistic / Vận tải',
 'Data Analyst, Logistic / Vận tải',
 'Phân tích dữ liệu, An ninh mạng, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Logistic / Vận tải, Thương mại điện tử',
 'Data Analyst, IT - Phần mềm, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Tài chính',
 'Nghiên cứu thị trường (Market Research), Nhân sự, IT - Phần mềm, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Phân tích dữ liệu, Tài chính',
 'Data Analyst, Phát thanh / Truyền hình',
 'Data Analyst, Bất động sản, Thương mại điện tử, IT - Phần mềm',
 'Thu hồi nợ, Tài chính, Ngân hàng',
 'Data Analyst, Ngân hàng',
 'Phân tích dữ liệu, Kiểm toán, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Ngân hàng, Tài chính, Bảo hiểm',
 'Phân tích dữ liệu, Thương mại điện tử, Logistic / Vận tải',
 'Phân tích dữ liệu, Chính phủ/Dịch vụ công',
 'Quản lý cơ sở vật chất',
 'Data Analyst, IT - Phần mềm, Kế toán, Tài chính',
 'Data Scientist, Chứng khoán, IT - Phần mềm',
 'Data Analyst, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần mềm',
 'Data Engineer',
 'Phân tích dữ liệu, Năng lượng / Môi trường, Xây dựng',
 'Business Analyst (Phân tích nghiệp vụ)',
 'Kinh doanh phần mềm, B2C',
 'Data Engineer, IT - Phần mềm, Ngân hàng',
 'Data Analyst, IT - Phần cứng và máy tính, Chính phủ/Dịch vụ công, In ấn / Xuất bản',
 'Business Intelligence, Marketing / Quảng cáo, Quan hệ công chúng',
 'Business Intelligence',
 'Business Intelligence, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Business Intelligence, Marketing / Quảng cáo, Game, Ngân hàng',
 'Business Intelligence, Ngân hàng, Tài chính, Bảo hiểm',
 'Business Intelligence, IT - Phần mềm',
 'Business Intelligence, Marketing / Quảng cáo',
 'Business Intelligence, IT - Phần mềm, Thương mại điện tử, Ngân hàng',
 'Data Labeling (Gán nhãn dữ liệu)',
 'Backend Developer, IT - Phần mềm',
 'Software Engineer',
 'Data Analyst, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần mềm',
 'Business Analyst (Phân tích nghiệp vụ), IT - Phần mềm, Ngân hàng',
 'Business Analyst (Phân tích nghiệp vụ), IT - Phần mềm',
 'Phân tích dữ liệu, Chính phủ/Dịch vụ công, Báo chí, Tài chính',
 'Data Analyst, Logistic / Vận tải, Kho vận',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Sản xuất',
 'Data Analyst, Nhân sự',
 'Phân tích dữ liệu, Giáo dục / Đào tạo',
 'Business Intelligence, Tài chính',
 'Business Intelligence, Kế toán, Logistic / Vận tải',
 'Business Intelligence, Chăm sóc sức khỏe / Làm đẹp, Giáo dục / Đào tạo, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Thương mại điện tử, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Du lịch, Marketing / Quảng cáo, IT - Phần mềm',
 'Business Intelligence, Marketing / Quảng cáo, Du lịch',
 'Business Intelligence, Thương mại điện tử, Logistic / Vận tải, Kho vận',
 'Product Analyst/Research, Viễn thông, IT - Phần mềm',
 'Product Analyst/Research, Giáo dục / Đào tạo, Marketing / Quảng cáo, Thương mại điện tử',
 'Chuyên môn khác, IT - Phần mềm',
 'Kiểm soát và báo cáo tài chính, Tài chính, Ngân hàng',
 'Product Analyst/Research, Game, Marketing / Quảng cáo',
 'Product Analyst/Research',
 'Data Engineer, IT - Phần mềm, Ngân hàng, Tài chính',
 'Data Engineer, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Sản xuất, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Thương mại điện tử',
 'Data Engineer, IT - Phần mềm, Tài chính, Ngân hàng',
 'Data Engineer, Điện toán đám mây (Cloud)',
 'Data Engineer, Tài chính, Ngân hàng, IT - Phần mềm',
 'Data Engineer, Ngân hàng, Tài chính, Điện toán đám mây (Cloud)',
 'Data Engineer, An ninh mạng, Công nghệ kỹ thuật',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Ngân hàng',
 'Data Engineer, IT - Phần cứng và máy tính',
 'Data Scientist, Game',
 'Data Scientist',
 'Data Scientist, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm, Chứng khoán',
 'Công nhân vận hành máy, Lao động phổ thông',
 'Chuyên môn Điện/Điện tử/Viễn thông khác',
 'AI Engineer, IT - Phần mềm, Viễn thông, Bưu chính',
 'AI Engineer, Xây dựng, Thiết kế / Kiến trúc, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, An ninh mạng',
 'AI Engineer, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Kỹ thuật điện/điện tử, Điện / Điện tử / Điện lạnh',
 'Bán hàng kỹ thuật IT, B2B, B2C, B2G',
 'AI Engineer, IT - Phần mềm, Điện / Điện tử / Điện lạnh, Công nghệ kỹ thuật',
 'AI Engineer',
 'AI Engineer, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'AI Engineer, IT - Phần mềm, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'AI Engineer, IT - Phần mềm, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, An ninh mạng',
 'Digital Marketing, Marketing / Quảng cáo',
 'Animation Design, Marketing / Quảng cáo, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Animation Design, Mỹ thuật / Nghệ thuật / Điện ảnh, Marketing / Quảng cáo',
 'Trợ lý/Thư ký, Thiết kế / Kiến trúc',
 'AI Engineer, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần cứng và máy tính',
 'Tích hợp hệ thống, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'Kỹ sư phân tích yêu cầu, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Sales IT Phần mềm khác, IT - Phần mềm, Viễn thông, B2B',
 'AI Engineer, IT - Phần mềm, Y tế / Dược phẩm',
 'IT Project Manager, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Thương mại điện tử',
 'Content Marketing, Giáo dục / Đào tạo, Marketing / Quảng cáo, Báo chí',
 'Chuyên môn Công nghệ thông tin khác',
 'AI Engineer, IT - Phần mềm, Tài chính, Ngân hàng',
 'Hoạch định tài chính, Tài chính, Bất động sản, Ngân hàng',
 'Chuyên môn khác, Công nghệ kỹ thuật, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Sales Kỹ thuật khác, Xây dựng, B2B, Direct Sales',
 'AI Engineer, Viễn thông, Công nghệ kỹ thuật',
 'Chuyên môn Phim và truyền hình/Báo chí/Xuất bản khác, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Social Content, Marketing / Quảng cáo',
 'AI Engineer, Hàng không',
 'Vận hành sàn thương mại điện tử, Thương mại điện tử',
 'AI Engineer, Thương mại điện tử',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Game',
 'Chuyên môn Điện tử/Phần cứng khác',
 'Social Media, Marketing / Quảng cáo, Bất động sản',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Digital Marketing',
 'AI Engineer, Giáo dục / Đào tạo, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Công nghệ kỹ thuật',
 'Photographer/Video Editor',
 'Kỹ thuật IT, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Chuyên môn Quảng cáo/Sáng tạo khác, Giáo dục / Đào tạo, Marketing / Quảng cáo, IT - Phần mềm',
 'Digital Marketing, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Giáo viên Tin học',
 'System Engineer',
 'Tích hợp hệ thống, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Kỹ sư tự động hóa, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'AI Engineer, IT - Phần mềm, Game',
 'AI Engineer, IT - Phần mềm, Game, Điện toán đám mây (Cloud)',
 'Database Administrator (DBA)',
 'System Administrator, IT - Phần cứng và máy tính',
 'Database Administrator (DBA), Tài chính, Ngân hàng, IT - Phần mềm',
 'Database Administrator (DBA), Kế toán',
 'Database Administrator (DBA), IT - Phần mềm',
 'Database Administrator (DBA), IT - Phần mềm, Sản xuất, IT - Phần cứng và máy tính',
 'Database Administrator (DBA), IT - Phần cứng và máy tính',
 'Data Analyst, IT - Phần mềm, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần mềm, Ngân hàng, Tài chính',
 'Data Analyst, Tài chính, Ngân hàng',
 'Product Analyst/Research, Nhân sự, Thương mại điện tử',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Viễn thông',
 'AI Engineer, IT - Phần mềm, Ngân hàng',
 'IT Project Manager',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Công nghệ kỹ thuật',
 'Software Engineer, IT - Phần mềm',
 'Database Administrator (DBA), Tài chính, Ngân hàng',
 'Data Scientist, Ngân hàng, Tài chính, IT - Phần mềm',
 'Data Analyst, Sản xuất',
 'Phân tích dữ liệu, Y tế / Dược phẩm',
 'Mã hóa và bảo mật dữ liệu, Game',
 'Chuyên môn khác, Thương mại điện tử',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Điện / Điện tử / Điện lạnh',
 'Phân tích dữ liệu, Tài chính, Kế toán, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, IT - Phần mềm, Viễn thông, Nhân sự',
 'Business Intelligence, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Database Administrator (DBA), IT - Phần mềm, Viễn thông',
 'Data Engineer, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Game',
 'Phân tích dữ liệu, IT - Phần mềm',
 'Chuyên môn Marketing, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Kho vận, Y tế / Dược phẩm',
 'Product Analyst/Research, Thương mại điện tử',
 'Data Engineer, IT - Phần mềm, Thương mại điện tử',
 'Data Scientist, An ninh mạng, Ngân hàng, IT - Phần mềm',
 'AI Engineer, Game',
 'Thiết kế đồ họa (Graphic Design), Thiết kế / Kiến trúc',
 'Photographer/Video Editor, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'AI Engineer, IT - Phần mềm, Ngân hàng, Tài chính',
 'Sales IT Phần mềm khác, IT - Phần mềm, Viễn thông, B2B, Direct Sales',
 'Database Administrator (DBA), IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Analyst, Viễn thông',
 'Data Analyst, IT - Phần mềm, Game, Marketing / Quảng cáo',
 'Business Intelligence, Tài chính, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Thương mại điện tử, Logistic / Vận tải, Nhân sự',
 'Chuyên môn Market Research and Analysis khác, Marketing / Quảng cáo, Ngân hàng, Hàng không',
 'Business Analyst (Phân tích nghiệp vụ), Logistic / Vận tải, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Thương mại điện tử',
 'Phân tích dữ liệu, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Product Analyst/Research, IT - Phần mềm, IT - Phần cứng và máy tính, Giáo dục / Đào tạo',
 'Data Engineer, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Engineer, IT - Phần mềm, Y tế / Dược phẩm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'QA Engineer',
 'Data Scientist, IT - Phần mềm, Thương mại điện tử',
 'Data Scientist, Tài chính, Ngân hàng, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm, IT - Phần cứng và máy tính, Năng lượng / Môi trường',
 'AI Engineer, IT - Phần mềm, Công nghệ kỹ thuật, IT - Phần cứng và máy tính',
 'AI Engineer, IT - Phần mềm, Marketing / Quảng cáo',
 'Concept Artist, Phát thanh / Truyền hình',
 'Data Analyst, Game, IT - Phần mềm',
 'Data Analyst, Giáo dục / Đào tạo',
 'Phân tích dữ liệu, Ngân hàng, Tài chính, Kế toán',
 'Chuyên môn khác, Tài chính, Chứng khoán, Kế toán',
 'Phân tích dữ liệu, Công nghệ kỹ thuật, Hàng hải',
 'Business Intelligence, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Data Scientist, Tài chính, Công nghệ kỹ thuật, Năng lượng / Môi trường',
 'Data Scientist, Năng lượng / Môi trường, Tài chính, Công nghệ kỹ thuật',
 'Giáo viên bộ môn khác, IT - Phần mềm, Cơ khí / Tự động hóa, Công nghệ kỹ thuật',
 'Chuyên môn khác, Bảo hiểm, Tài chính',
 'Quản lý dự án kỹ thuật, IT - Phần mềm, Thương mại điện tử',
 'Phân tích dữ liệu, Tài chính, Ngân hàng',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần mềm, Tài chính, Sản xuất',
 'Data Analyst, IT - Phần mềm, Bảo hiểm, Tài chính',
 'Business Intelligence, Tài chính, Chứng khoán',
 'Data Engineer, Năng lượng / Môi trường, Công nghệ kỹ thuật, IT - Phần mềm',
 'Data Engineer, Điện toán đám mây (Cloud), Thương mại điện tử, IT - Phần mềm',
 'Data Engineer, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Engineer, Thương mại điện tử, Nhà hàng / Khách sạn',
 'Trợ lý/Thư ký, Ngân hàng',
 'Software Tester (Automation & Manual), IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Viễn thông, Tài chính',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Viễn thông',
 'AI Researcher, Tài chính, Bảo hiểm',
 'Chuyên môn khác',
 'AI Engineer, Marketing / Quảng cáo, Công nghệ kỹ thuật',
 'AI Researcher',
 'Kinh doanh phần mềm, B2B',
 'Data Analyst, Quan hệ công chúng, Marketing / Quảng cáo, Chăm sóc sức khỏe / Làm đẹp',
 'Phân tích dữ liệu, Logistic / Vận tải, Kho vận',
 'Phân tích dữ liệu, Viễn thông',
 'Phân tích dữ liệu, Thực phẩm / Đồ uống, Y tế / Dược phẩm',
 'Data Analyst, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Thương mại điện tử',
 'Chuyên môn khác, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, Giáo dục / Đào tạo, IT - Phần mềm',
 'Phóng viên/Biên tập viên tin tức',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG, May mặc / Thời trang',
 'GIS Engineer, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Công nghệ kỹ thuật',
 'Chuyên môn khác, Chứng khoán, Tài chính',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Điện toán đám mây (Cloud)',
 'AI Engineer, Bất động sản, IT - Phần mềm',
 'Fullstack Developer, IT - Phần mềm',
 'AI Engineer, Tài chính, Logistic / Vận tải, Bảo hiểm',
 'Chuyên môn Marketing/PR/Quảng cáo khác, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Content Marketing, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Biên kịch, Phát thanh / Truyền hình, Marketing / Quảng cáo, Chăm sóc sức khỏe / Làm đẹp',
 'Vận hành chung',
 'Product Owner/Product Manager, IT - Phần mềm, IT - Phần cứng và máy tính, Điện toán đám mây (Cloud)',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, Ngân hàng',
 'AI Engineer, IT - Phần mềm, May mặc / Thời trang',
 'Data Analyst, IT - Phần mềm, Tài chính, Ngân hàng',
 'Phân tích dữ liệu, Bất động sản, Tài chính',
 'Business Intelligence, Logistic / Vận tải, Thương mại điện tử',
 'Thiết kế đồ họa (Graphic Design), Thương mại điện tử, Marketing / Quảng cáo, Thiết kế / Kiến trúc',
 'AI Engineer, IT - Phần mềm, Ngân hàng, Bảo hiểm',
 'Phân tích dữ liệu, Tài chính, IT - Phần mềm',
 'Phân tích dữ liệu, IT - Phần mềm, Viễn thông, Bưu chính',
 'Phân tích dữ liệu, Thương mại điện tử',
 'Product Analyst/Research, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Viễn thông, Ngân hàng',
 'Data Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Data Analyst, IT - Phần mềm, Y tế / Dược phẩm',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Tài chính',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Y tế / Dược phẩm',
 'Data Scientist, IT - Phần mềm, Y tế / Dược phẩm',
 'Business Analyst (Phân tích nghiệp vụ), Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'AI Engineer, IT - Phần mềm, Y tế / Dược phẩm, An ninh mạng',
 'AI Engineer, IT - Phần cứng và máy tính, An ninh mạng, Chứng khoán',
 'DevOps Engineer, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Tài chính, Chứng khoán',
 'Chief Technology Officer (CTO), An ninh mạng, IT - Phần cứng và máy tính',
 'Tư vấn CNTT/IT consultant, IT - Phần mềm, Công nghệ kỹ thuật, Điện toán đám mây (Cloud)',
 'Kinh doanh phần mềm, IT - Phần mềm, Marketing / Quảng cáo, B2B, B2C, Direct Sales, Telesales, Online Sales',
 'AI Engineer, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'AI Engineer, IT - Phần mềm, Viễn thông',
 'Database Administrator (DBA), IT - Phần mềm, Điện toán đám mây (Cloud), IT - Phần cứng và máy tính',
 'Data Analyst, IT - Phần cứng và máy tính, IT - Phần mềm, Sản xuất',
 'Data Analyst, Marketing / Quảng cáo, Du lịch',
 'Chuyên môn Nhân sự/Hành chính/Pháp chế khác, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Tài chính, Ngân hàng, Chứng khoán',
 'Phân tích dữ liệu, Sản xuất, Kế toán, May mặc / Thời trang',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG, May mặc / Thời trang, Marketing / Quảng cáo',
 'Product Analyst/Research, IT - Phần mềm, Marketing / Quảng cáo',
 'Product Analyst/Research, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'AI Engineer, Y tế / Dược phẩm, Marketing / Quảng cáo',
 'AI Engineer, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Logistic / Vận tải',
 'Technical Director, IT - Phần mềm',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm',
 'Data Analyst, Ngân hàng, Tài chính',
 'Data Analyst, Chính phủ/Dịch vụ công, IT - Phần mềm',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Kế toán, May mặc / Thời trang',
 'Data Analyst, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Sản xuất, Bất động sản',
 'Phân tích dữ liệu, Thực phẩm / Đồ uống, Kiểm toán',
 'Business Intelligence, Thực phẩm / Đồ uống',
 'Data Engineer, IT - Phần mềm, Chính phủ/Dịch vụ công',
 'Data Engineer, IT - Phần cứng và máy tính, An ninh mạng',
 'Data Scientist, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Quản trị rủi ro, Ngân hàng, Tài chính',
 'Data Analyst, Tài chính, IT - Phần mềm',
 'Phân tích dữ liệu, Điện / Điện tử / Điện lạnh',
 'Data Engineer, Thương mại điện tử',
 'Data Scientist, Điện toán đám mây (Cloud), IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Kinh doanh phần mềm, Tài chính, Ngân hàng, Kế toán, B2B',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Software Engineer, IT - Phần mềm, Cơ khí / Tự động hóa',
 'Content Creator, Chăm sóc sức khỏe / Làm đẹp, Y tế / Dược phẩm',