# VS code cũng đẹp mà
Tui yêu cái đẹp, thấy cái gì đẹp là tui lưu lại hết à
Tui muốn sản phẩm mk làm ra có sự chỉnh chu, áp dụng được vào thực tiễn, thực sự có ích cho đời

In [2]:
import random

# https://www.fileformat.info/info/unicode/category/So/list.htm

list = ['''Dừa lòng :)) \U0001F965''',
        '\U0001F335 \U0001F335 \U0001F335',
        'Tóc giả giả \U0001FAAD',
        '9094 -> Mồm\U0001F415 vó\U0001F434',
        'Kay \U0001F332 \U0001F333 \U0001F99D \U0001F423',
        'Tăng Phúc \U0001F9A6',
        '2 Neko \U0001F451 \U0001F40D \U0001F63A \U0001F638 \U0001F639 \U0001F640',
        'Nui \U0001F35C',
        'ST \U0001F43A \U0001F427', 
        '\U0001F33B', '\U0001F337', '\U0001F338', '\U0001F339', '\U0001F33A', '\U0001F33C', '\U0001F33E', '\U0001F340']
# print(*list, sep='\n')

random_item = (random.choice(list) + ' \u2740 '+ random.choice(list) + ' \u2740 '+random.choice(list) + ' \u2740 ' + '\n')*5
print(random_item)

Kay 🌲 🌳 🦝 🐣 ❀ Tóc giả giả 🪭 ❀ 🍀 ❀
Kay 🌲 🌳 🦝 🐣 ❀ Tóc giả giả 🪭 ❀ 🍀 ❀
Kay 🌲 🌳 🦝 🐣 ❀ Tóc giả giả 🪭 ❀ 🍀 ❀
Kay 🌲 🌳 🦝 🐣 ❀ Tóc giả giả 🪭 ❀ 🍀 ❀
Kay 🌲 🌳 🦝 🐣 ❀ Tóc giả giả 🪭 ❀ 🍀 ❀

In [1]:
# import libraries 

import numpy as np
import pandas as pd

#Vẽ biểu đồ
import matplotlib.pyplot as plt 

# Vẽ biểu đồ nhiệt
import seaborn as sns

from collections import Counter

In [2]:
# review file data
filename = r"E:\Chuyển từ download sang\A Học tập Bách Khoa\ĐA2\Đồ án 2 _ 2025\Project_full\Crawl_job\Data_raw\data_careerviet.csv"

df=pd.read_csv(filename)
df

,index,job_url,search_keyword,job_title,company_name,location,posted_date,deadline_date,category,work_type,salary,experience,level_employee,education_level,description,requirements,benefits,source_site
0,1,https://careerviet.vn/vi/tim-viec-lam/ha-noi-b...,Data Analyst,[Hà Nội] Business Intelligence Executive (Data...,Công Ty Cổ Phần Diana Unicharm,Hà Nội,27/03/2026,25/04/2026,"CNTT - Phần mềm , Thương mại điện tử , Ngành khác",Nhân viên chính thức,28 Tr - 40 Tr VND,3 - 5 Năm,Nhân viên,Đại học,"Phân tích, xử lý Dữ liệu & BI. Data Analytics ...","Tốt nghiệp Đại học các ngành Kinh tế, Ngoại th...",Laptop. Chế độ bảo hiểm. Du Lịch. Du lịch nước...,careerviet.vn
1,2,https://careerviet.vn/vi/tim-viec-lam/software...,Data Analyst,Software Architect,Công ty TNHH Viettel - CHT,Hà Nội,20/04/2026,04/05/2026,"CNTT - Phần mềm , CNTT - Phần cứng / Mạng",Nhân viên chính thức,Cạnh tranh,Trên 5 Năm,Nhân viên,Đại học,Chúng tôi đang tìm kiếm Software Architect tài...,Tốt nghiệp các ngành liên quan đến Công nghệ t...,Chế độ bảo hiểm. Du Lịch. Chế độ thưởng. Chăm ...,careerviet.vn
2,3,https://careerviet.vn/vi/tim-viec-lam/software...,Data Analyst,Software Architect,Công ty TNHH Viettel - CHT,Hà Nội,10/04/2026,09/05/2026,"CNTT - Phần mềm , CNTT - Phần cứng / Mạng",Nhân viên chính thức,Cạnh tranh,Trên 3 Năm,Nhân viên,Đại học,Chúng tôi đang tìm kiếm Software Architect tài...,Tốt nghiệp các ngành liên quan đến Công nghệ t...,Chế độ bảo hiểm. Du Lịch. Chế độ thưởng. Chăm ...,careerviet.vn
3,4,https://careerviet.vn/vi/tim-viec-lam/software...,Data Analyst,Software Architect,Công ty TNHH Viettel - CHT,Hà Nội,03/04/2026,02/05/2026,"CNTT - Phần mềm , CNTT - Phần cứng / Mạng",Nhân viên chính thức,Cạnh tranh,Trên 3 Năm,Nhân viên,Đại học,Chúng tôi đang tìm kiếm Software Architect tài...,Tốt nghiệp các ngành liên quan đến Công nghệ t...,Chế độ bảo hiểm. Du Lịch. Chế độ thưởng. Chăm ...,careerviet.vn
4,5,https://careerviet.vn/vi/tim-viec-lam/ai-softw...,Data Analyst,AI Software Engineer (Python/Go/C/C++ Backend ...,Ngân Hàng TMCP Quân Đội,Hà Nội,13/04/2026,12/05/2026,"Ngân hàng , CNTT - Phần mềm , CNTT - Phần cứng...",Nhân viên chính thức,Cạnh tranh,Trên 1 Năm,Nhân viên,Đại học,Xây dựng phát triển các sản phẩm AI có khả năn...,Tốt nghiệp Đại học các chuyên ngành: Công nghệ...,Laptop. Chế độ bảo hiểm. Du Lịch. Phụ cấp. Du ...,careerviet.vn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,915,https://careerviet.vn/vi/tim-viec-lam/chuyen-v...,AI Engineer,Chuyên viên Thiết kế Hội thoại AI (AI Conversa...,Công ty Cổ phần Masscom Việt Nam,Hà Nội,11/06/2026,11/07/2026,"Quảng cáo / Đối ngoại / Truyền Thông , Giáo dụ...",Nhân viên chính thức,15 Tr - 25 Tr VND,Chưa có kinh nghiệm,Nhân viên,NaN,Masscom là doanh nghiệp công nghệ Việt Nam với...,1/ Kiến thức và kinh nghiệm. Tối thiểu 2 năm k...,Laptop. Chế độ bảo hiểm. Du Lịch. Phụ cấp. Đồn...,careerviet.vn
915,916,https://careerviet.vn/vi/tim-viec-lam/ai-engin...,AI Engineer,"AI Engineer (Python, LLM & AI Agents)",Công ty Cổ phần Masscom Việt Nam,Hà Nội,11/06/2026,11/07/2026,"CNTT - Phần mềm , Y tế / Chăm sóc sức khỏe / T...",Nhân viên chính thức,18 Tr - 25 Tr VND,2 - 4 Năm,Nhân viên,NaN,"Với vị trí này bạn sẽ tham gia nghiên cứu, thi...",1/ Kiến thức & Nền tảng. Tốt nghiệp Đại học ch...,Laptop. Chế độ bảo hiểm. Du Lịch. Phụ cấp. Đồn...,careerviet.vn
916,917,https://careerviet.vn/vi/tim-viec-lam/ky-su-tr...,AI Engineer,Kỹ sư Trí tuệ nhân tạo (AI Engineer),Công ty Cổ phần Tập đoàn Hoa Sen,Hồ Chí Minh,10/06/2026,10/07/2026,"CNTT - Phần mềm , Bán lẻ / Bán sỉ , CNTT - Phầ...",Nhân viên chính thức,Cạnh tranh,2 - 3 Năm,Nhân viên,Đại học,"Nghiên cứu, phát triển và triển khai các thuật...",Tốt nghiệp Đại học trở lên chuyên ngành Công n...,Chế độ bảo hiểm. Phụ cấp. Đồng phục. Chăm sóc ...,careerviet.vn
917,918,https://careerviet.vn/vi/tim-viec-lam/it-engin...,Data Modeler,IT Engineer - Identity & Access Management (Gl...,Summit Polymers Vietnam Co Ltd.,Hồ Chí Minh,12/06/2026,31/07/2026,"CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Sả...",Nhân viên chính thức,Cạnh tranh,5 - 7 Năm,Nhân viên,NaN,Summary:. Motivated Software Developer and res...,"REQUIRED KNOWLEDGE, SKILLS AND ABILITIES:. Wor...",Laptop. Chế độ bảo hiểm. Du Lịch. Đồng phục. C...,careerviet.vn
918,919,https://careerviet.vn/vi/tim-viec-lam/middle-b...,Data Modeler,Middle Backend Engineer,Công ty Cổ phần Masscom Việt Nam,Hà Nội,10/06/2026,10/07/2026,"CNTT - Phần mềm , Bưu chính viễn thông , Y tế ...",Nhân viên chính thức,15 Tr - 25 Tr VND,2 - 4 Năm,Nhân viên,NaN,Thương hiệu Meup (trực thuộc Masscom) là đơn v...,1/ Trình độ & Kinh nghiệm. Tốt nghiệp Đại học ...,Laptop. Chế độ bảo hiểm. Du Lịch. Phụ cấp. Đồn...,careerviet.vn

In [5]:
# Kiểm tra kiểu dữ liệu
df.dtypes

index               int64
job_url            object
search_keyword     object
job_title          object
company_name       object
location           object
posted_date        object
deadline_date      object
category           object
work_type          object
salary             object
experience         object
level_employee     object
education_level    object
description        object
requirements       object
benefits           object
source_site        object
dtype: object

In [6]:
# Thống kê các cột chứa giá trị text

# percentile list
perc = [.25, .50, .75]
  
# list of dtypes to include
include = ['object']
  
# calling describe method
desc = df.describe(percentiles=perc, include=include)
  
# display
desc

,job_url,search_keyword,job_title,company_name,location,posted_date,deadline_date,category,work_type,salary,experience,level_employee,education_level,description,requirements,benefits,source_site
count,886,886,883,874,883,864,883,883,882,883,801,883,419,862,882,838,886
unique,886,18,690,319,30,69,96,362,6,107,63,7,4,686,723,207,1
top,https://careerviet.vn/vi/tim-viec-lam/ha-noi-b...,Data Analyst,Business Analyst,Ngân Hàng TMCP Quân Đội,Hồ Chí Minh,23/04/2026,30/06/2026,CNTT - Phần mềm,Nhân viên chính thức,Cạnh tranh,3 - 5 Năm,Nhân viên,Đại học,Kiểm tra hóa đơn cùng các chứng từ liên quan đ...,Bachelor’s degree in engineering field or high...,Chế độ bảo hiểm. Du Lịch. Chế độ thưởng. Chăm ...,careerviet.vn
freq,1,345,18,46,395,51,88,142,843,627,103,687,354,7,7,100,886

In [7]:
# Đếm số giá trị duy nhất từng cột
df.nunique()

index              886
job_url            886
search_keyword      18
job_title          690
company_name       319
location            30
posted_date         69
deadline_date       96
category           362
work_type            6
salary             107
experience          63
level_employee       7
education_level      4
description        686
requirements       723
benefits           207
source_site          1
dtype: int64

In [10]:
# Cột search_keyword có bao nhiêu giá trị duy nhất
df['search_keyword'].unique().tolist()

['Data Analyst',
 'Business Intelligence',
 'Data Visualization',
 'Product Analyst',
 'Marketing Analyst',
 'Data Engineer',
 'Data Warehouse',
 'ETL',
 'Cloud Data',
 'Data Scientist',
 'Machine Learning',
 'AI Engineer',
 'Computer Vision Engineer',
 'Algorithm Engineer',
 'Database Administrator',
 'Data Modeler',
 'Analytics Engineer',
 'Data Architect']

In [11]:
# Cột location có bao nhiêu giá trị duy nhất
df['location'].unique().tolist()

['Hà Nội',
 'Hồ Chí Minh',
 'Bà Rịa - Vũng Tàu',
 'Bình Dương',
 'Hải PhòngHà Nội',
 'Long An',
 'Hồ Chí MinhHà Nội',
 'Hồ Chí MinhBình Dương',
 'Tây Ninh',
 'Hà NộiHải Dương',
 'Bình Định',
 'Hà NộiHồ Chí Minh',
 'Đồng Nai',
 'Đồng NaiHồ Chí Minh',
 'Quảng NamQuảng NgãiĐà Nẵng',
 'Hồ Chí MinhCần Thơ',
 'Hưng Yên',
 'Dak Lak',
 'Cần Thơ',
 'Sóc Trăng An Giang',
 'Quảng Ngãi',
 'Hải Phòng',
 'Hà NộiHưng Yên',
 'Đà Nẵng',
 'Hà NộiBắc NinhHưng Yên',
 nan,
 'Hà Nội Hải Phòng Quảng Ninh',
 'Hồ Chí Minh Bình Dương Bà Rịa - Vũng Tàu',
 'Lâm Đồng',
 'Hồ Chí Minh Đồng Nai',
 'Hà NộiBắc Ninh']

In [12]:
# Cột salary có bao nhiêu giá trị duy nhất
df['salary'].unique().tolist()

['28 Tr - 40 Tr VND',
 'Cạnh tranh',
 '15 Tr - 30 Tr VND',
 '10 Tr - 20 Tr VND',
 '20 Tr - 25 Tr VND',
 '25 Tr - 35 Tr VND',
 '15 Tr - 20 Tr VND',
 '15 Tr - 25 Tr VND',
 '18 Tr - 22 Tr VND',
 '8 Tr - 10 Tr VND',
 '30 Tr - 50 Tr VND',
 '10 Tr - 25 Tr VND',
 '30 Tr - 60 Tr VND',
 '20 Tr - 40 Tr VND',
 '12 Tr - 18 Tr VND',
 '8,000,000 - 8,000,000 VND',
 '12 Tr - 15 Tr VND',
 '12 Tr - 30 Tr VND',
 '13 Tr - 20 Tr VND',
 '11 Tr - 13 Tr VND',
 '3 Tr - 4 Tr VND',
 '12 Tr - 26 Tr VND',
 '10 Tr - 15 Tr VND',
 '20 Tr - 35 Tr VND',
 '6,5 Tr - 10 Tr VND',
 '4 Tr - 6 Tr VND',
 '2 Tr - 3 Tr VND',
 '12 Tr - 25 Tr VND',
 '30 Tr - 40 Tr VND',
 '800 - 1.100 USD',
 '20 Tr - 23 Tr VND',
 '20 Tr - 30 Tr VND',
 '25 Tr - 45 Tr VND',
 '12 Tr - 16 Tr VND',
 '35 Tr - 50 Tr VND',
 '18 Tr - 25 Tr VND',
 '9 Tr - 15 Tr VND',
 '9,000,000 - 11,000,000 VND',
 '12 Tr - 20 Tr VND',
 '18 Tr - 24 Tr VND',
 '10 Tr - 13 Tr VND',
 '18 Tr - 20 Tr VND',
 '7 Tr - 10 Tr VND',
 '16 Tr - 18 Tr VND',
 '28 Tr - 30 Tr VND',
 '12 Tr - 40 Tr VND',
 '13 Tr - 25 Tr VND',
 '10 Tr - 16 Tr VND',
 '15 Tr - 33 Tr VND',
 '18 Tr - 35 Tr VND',
 '8 Tr - 15 Tr VND',
 '13 Tr - 18 Tr VND',
 '1,200 - 1,600 USD',
 '7 Tr - 12 Tr VND',
 '1 Tr - 3 Tr VND',
 '700 - 1.400 USD',
 '70 Tr - 90 Tr VND',
 '20 Tr - 45 Tr VND',
 '50 Tr - 60 Tr VND',
 '10 Tr - 18 Tr VND',
 'Lên đến 35 Tr VND',
 'Lên đến 25 Tr VND',
 'Lên đến 30 Tr VND',
 '15 Tr - 35 Tr VND',
 'Lên đến 40 Tr VND',
 '16 Tr - 35 Tr VND',
 '15 Tr - 23 Tr VND',
 '35 Tr - 45 Tr VND',
 '30 Tr - 42 Tr VND',
 '15 Tr - 16 Tr VND',
 '14 Tr - 20 Tr VND',
 '2.500 - 3.000 USD',
 'Trên 28 Tr VND',
 '18 Tr - 30 Tr VND',
 '26 Tr - 35 Tr VND',
 '35 Tr - 40 Tr VND',
 '3 Tr - 3,3 Tr VND',
 '2.900 - 3.000 USD',
 '20 Tr - 24 Tr VND',
 '32 Tr - 40 Tr VND',
 '15 Tr - 18 Tr VND',
 '4 Tr - 10 Tr VND',
 '12,000,000 - 15,000,000 VND',
 '1.100 - 1.100 USD',
 'Lên đến 8 Tr VND',
 '25 Tr - 38 Tr VND',
 '3.000 - 5.000 USD',
 '3 Tr - 12 Tr VND',
 '14 Tr - 17 Tr VND',
 nan,
 'Trên 20 Tr VND',
 '3 Tr - 5 Tr VND',
 '3 Tr - 3 Tr VND',
 '8 Tr - 12 Tr VND',
 '12 Tr - 14 Tr VND',
 '17 Tr - 25 Tr VND',
 '15 Tr - 50 Tr VND',
 '15 Tr - 40 Tr VND',
 '30 Tr - 38 Tr VND',
 '16 Tr - 25 Tr VND',
 '25 Tr - 40 Tr VND',
 '1 Tr - 2 Tr VND',
 '40 Tr - 60 Tr VND',
 '40 Tr - 50 Tr VND',
 '30 Tr - 45 Tr VND',
 '35 Tr - 38 Tr VND',
 '25 Tr - 30 Tr VND',
 '10 Tr - 12 Tr VND']

In [14]:
# Cột work_type có bao nhiêu giá trị duy nhất
df['work_type'].unique().tolist()

['Nhân viên chính thức',
 nan,
 'Thực tập',
 'Nhân viên chính thức , Thực tập',
 'Nhân viên chính thức , Bán thời gian',
 'Bán thời gian , Thực tập',
 'Thời vụ/ Nghề tự do']

In [14]:
# Cột date_posted có bao nhiêu giá trị duy nhất
df['date_posted'].unique().tolist()

['2026-04-13',
 '2026-04-11',
 '2026-04-08',
 '2026-04-07',
 '2026-04-06',
 '2026-03-30',
 '2026-04-09',
 '2026-03-14',
 '2026-04-10',
 '2026-03-23',
 '2026-03-16',
 '2026-03-31',
 '2026-03-17',
 '2026-04-22',
 '2026-04-16',
 '2026-04-21',
 '2026-04-18',
 '2026-04-17',
 '2026-03-24',
 '2026-04-20',
 '2026-04-02',
 '2026-03-26',
 '2026-04-23',
 '2026-04-24',
 '2026-04-25',
 '2026-04-30',
 '2026-04-29',
 '2026-05-01',
 '2026-04-28',
 '2026-04-27',
 '2026-04-26',
 '2026-05-04',
 '2026-05-05',
 '2026-05-08',
 '2026-05-07',
 '2026-05-06',
 '2026-05-02',
 '2026-05-11',
 '2026-05-09',
 '2026-05-12',
 '2026-05-15',
 '2026-05-14',
 '2026-05-13',
 '2026-05-10',
 '2026-05-16',
 '2026-05-21',
 '2026-05-18',
 '2026-05-20',
 '2026-05-19',
 '2026-05-17',
 '2026-05-23',
 '2026-05-22']

In [15]:
# Cột deadline_date (ngày hết hạn nộp hồ sơ) có bao nhiêu giá trị duy nhất
df['deadline_date'].unique().tolist()

['13/05/2026',
 '30/06/2026',
 '08/05/2026',
 '07/05/2026',
 '30/04/2026',
 '05/05/2026',
 '03/05/2026',
 '02/05/2026',
 '01/05/2026',
 '29/04/2026',
 '09/05/2026',
 '31/05/2026',
 '23/05/2026',
 '15/05/2026',
 '10/05/2026',
 '15/06/2026',
 '16/04/2026',
 '04/05/2026',
 '28/04/2026',
 '27/04/2026',
 '26/04/2026',
 '25/04/2026',
 '23/04/2026',
 '24/04/2026',
 '22/04/2026',
 '20/04/2026',
 '19/04/2026',
 '18/04/2026',
 '17/04/2026',
 '15/04/2026',
 '06/05/2026',
 '22/05/2026',
 '16/05/2026',
 '18/05/2026',
 '17/05/2026',
 '06/06/2026',
 '30/05/2026',
 '02/06/2026',
 '21/05/2026',
 '14/05/2026',
 '20/05/2026',
 '11/05/2026',
 '31/07/2026',
 '18/06/2026',
 '30/11/2026',
 '01/06/2026',
 '24/05/2026',
 '25/05/2026',
 '29/05/2026',
 '28/05/2026',
 '26/05/2026',
 '03/06/2026',
 '04/06/2026',
 '07/06/2026',
 '05/06/2026',
 '17/06/2026',
 '09/06/2026',
 '05/07/2026',
 '10/06/2026',
 '08/06/2026',
 '12/06/2026',
 '11/06/2026',
 '14/06/2026',
 '13/06/2026',
 '20/06/2026',
 '19/06/2026',
 '16/06/2026',
 '22/06/2026',
 '21/06/2026']

In [16]:
# Cột category (phân loại job) có bao nhiêu giá trị duy nhất
df['category'].unique().tolist()

['CNTT - Phần mềm , Thương mại điện tử , Ngành khác',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Ngân hàng , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Vận chuyển / Giao nhận /  Kho vận',
 'Bán hàng / Kinh doanh , Ngân hàng , Bảo hiểm',
 'Tiếp thị / Marketing , Điện / Điện tử / Điện lạnh / Điện công nghiệp , Bán Hàng Kỹ Thuật',
 'Tài chính / Đầu tư',
 'Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh , Bưu chính viễn thông',
 'Ngân hàng , Tài chính / Đầu tư , CNTT - Phần mềm',
 'CNTT - Phần mềm , Thương mại điện tử , Bưu chính viễn thông',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Thương mại điện tử',
 'CNTT - Phần mềm',
 'Thống kê , Tài chính / Đầu tư , CNTT - Phần mềm',
 'Ngân hàng , CNTT - Phần mềm',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'Chứng khoán , Tài chính / Đầu tư , CNTT - Phần mềm',
 'Tiếp thị / Marketing , Bán hàng / Kinh doanh',
 'Nông nghiệp , Sản xuất / Vận hành sản xuất , Thu mua / Vật tư',
 'Ngân hàng , Tài chính / Đầu tư',
 'Dầu khí , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Bán hàng / Kinh doanh , Bưu chính viễn thông , CNTT - Phần cứng / Mạng',
 'Giáo dục / Đào tạo , CNTT - Phần mềm',
 'Bán hàng / Kinh doanh , Kế toán / Kiểm toán , Dệt may / Da giày / Thời trang',
 'Ngân hàng , Tài chính / Đầu tư , Thống kê',
 'CNTT - Phần mềm , Nhân sự',
 'Dịch vụ khách hàng , Thương mại điện tử , Bán lẻ / Bán sỉ',
 'Tài chính / Đầu tư , CNTT - Phần mềm',
 'Thống kê , CNTT - Phần mềm',
 'Xuất nhập khẩu , Vận chuyển / Giao nhận /  Kho vận',
 'CNTT - Phần mềm , Ngân hàng',
 'CNTT - Phần cứng / Mạng',
 'Chứng khoán , CNTT - Phần mềm',
 'Bán lẻ / Bán sỉ , Dệt may / Da giày / Thời trang',
 'Bán hàng / Kinh doanh',
 'Luật / Pháp lý',
 'Cơ khí / Ô tô / Tự động hóa , Điện / Điện tử / Điện lạnh / Điện công nghiệp , Sản xuất / Vận hành sản xuất',
 'Tiếp thị / Marketing , CNTT - Phần mềm',
 'Dược phẩm/ Hóa Mỹ Phẩm , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'CNTT - Phần mềm , Bán hàng / Kinh doanh , Sản xuất / Vận hành sản xuất',
 'Ngân hàng',
 'Tài chính / Đầu tư , Kế toán / Kiểm toán , Ngành khác',
 'Thương mại điện tử , Thống kê , CNTT - Phần mềm',
 'Thống kê , CNTT - Phần mềm , Tiếp thị / Marketing',
 'Tiếp thị trực tuyến , CNTT - Phần mềm , Thống kê',
 'Bán hàng / Kinh doanh , Hành chính / Thư ký , CNTT - Phần mềm',
 'Môi trường, CNTT - Phần mềm',
 'Quảng cáo / Đối ngoại / Truyền Thông , Thống kê , CNTT - Phần mềm',
 'CNTT - Phần mềm , Bảo hiểm',
 'Dịch vụ khách hàng , CNTT - Phần mềm',
 'Tiếp thị / Marketing , Thương mại điện tử , Bán lẻ / Bán sỉ',
 'Nhân sự , Bán hàng / Kinh doanh , Bán lẻ / Bán sỉ',
 'Cơ khí / Ô tô / Tự động hóa , Điện / Điện tử / Điện lạnh / Điện công nghiệp , Ngành khác',
 'Bán lẻ / Bán sỉ , Kế toán / Kiểm toán , Tài chính / Đầu tư',
 'Kế toán / Kiểm toán , Thực phẩm & Đồ uống , Tài chính / Đầu tư',
 'Hóa học , Cơ khí / Ô tô / Tự động hóa , Ngành khác',
 'Bất động sản , Bán lẻ / Bán sỉ',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , Luật / Pháp lý',
 'Thực phẩm & Đồ uống , Công nghệ sinh học , Công nghệ thực phẩm / Dinh dưỡng',
 'CNTT - Phần mềm , Thương mại điện tử , Bán lẻ / Bán sỉ',
 'Sản xuất / Vận hành sản xuất',
 'Nhân sự',
 'CNTT - Phần mềm , Điện / Điện tử / Điện lạnh / Điện công nghiệp , Mỹ thuật / Nghệ thuật / Thiết kế',
 'Kế toán / Kiểm toán',
 'CNTT - Phần mềm , Sản xuất / Vận hành sản xuất',
 'CNTT - Phần mềm , Bán hàng / Kinh doanh',
 'CNTT - Phần mềm , Ngân hàng , Bảo hiểm',
 'CNTT - Phần mềm , Ngân hàng , CNTT - Phần cứng / Mạng',
 'Hàng gia dụng / Chăm sóc cá nhân , Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư',
 'Nhân sự , Mới tốt nghiệp / Thực tập , Hành chính / Thư ký',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , Cơ khí / Ô tô / Tự động hóa',
 'Tiếp thị / Marketing , Thương mại điện tử , CNTT - Phần mềm',
 'CNTT - Phần mềm , Ngân hàng , Chứng khoán',
 'Sản xuất / Vận hành sản xuất , Đồ gỗ , Nội ngoại thất',
 'Tiếp thị / Marketing',
 'Ngành khác',
 'Vận chuyển / Giao nhận /  Kho vận , Thực phẩm & Đồ uống , Thu mua / Vật tư',
 'Ngân hàng , Chứng khoán , Tài chính / Đầu tư',
 'Kế toán / Kiểm toán , Luật / Pháp lý , Tài chính / Đầu tư',
 'Ngân hàng , Chứng khoán , CNTT - Phần mềm',
 'Tư vấn , Thống kê , Quảng cáo / Đối ngoại / Truyền Thông',
 'Tư vấn , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Ngân hàng , Tài chính / Đầu tư , Bán hàng / Kinh doanh',
 'Kế toán / Kiểm toán , Thống kê , Tài chính / Đầu tư',
 'Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh , Chứng khoán',
 'Kế toán / Kiểm toán , Bán hàng / Kinh doanh , Thống kê',
 'Bán lẻ / Bán sỉ , Thương mại điện tử , Cơ khí / Ô tô / Tự động hóa',
 'Thu mua / Vật tư , Xuất nhập khẩu',
 'Mới tốt nghiệp / Thực tập , Dịch vụ khách hàng , Sản xuất / Vận hành sản xuất',
 'Dịch vụ khách hàng , CNTT - Phần mềm , Mới tốt nghiệp / Thực tập',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , CNTT - Phần mềm',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , Mới tốt nghiệp / Thực tập',
 'CNTT - Phần mềm , Tư vấn , Bán hàng / Kinh doanh',
 'CNTT - Phần mềm , Ngân hàng , Tài chính / Đầu tư',
 'Ngân hàng , Tài chính / Đầu tư , Quản lý điều hành',
 'CNTT - Phần mềm , Bán hàng / Kinh doanh , Chứng khoán',
 'Bán hàng / Kinh doanh , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Ngành khác , Ngân hàng , CNTT - Phần mềm',
 'Ngân hàng , Kế toán / Kiểm toán',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Tư vấn',
 'Ngân hàng , CNTT - Phần mềm , Tài chính / Đầu tư',
 'Giáo dục / Đào tạo',
 'Thương mại điện tử , CNTT - Phần mềm',
 'CNTT - Phần mềm , Công nghệ thực phẩm / Dinh dưỡng , Hóa học',
 'CNTT - Phần mềm , Ngành khác',
 'Kế toán / Kiểm toán , Vận chuyển / Giao nhận /  Kho vận , Tài chính / Đầu tư',
 'Ngân hàng , Nhân sự , Bảo hiểm',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , Ngân hàng',
 'Xuất nhập khẩu , Nội ngoại thất',
 'Cơ khí / Ô tô / Tự động hóa , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Dịch vụ khách hàng , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'CNTT - Phần mềm , Bán lẻ / Bán sỉ , CNTT - Phần cứng / Mạng',
 'Kế toán / Kiểm toán , Hành chính / Thư ký , Ngân hàng',
 'Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp , CNTT - Phần mềm',
 'Xây dựng',
 'Thu mua / Vật tư , Bán hàng / Kinh doanh , Thực phẩm & Đồ uống',
 'Kế toán / Kiểm toán , Xây dựng , Ngân hàng',
 'CNTT - Phần mềm , Ngân hàng , Dịch vụ khách hàng',
 'Tư vấn , CNTT - Phần mềm , Tiếp thị / Marketing',
 'Ngân hàng , Kế toán / Kiểm toán , Tài chính / Đầu tư',
 'Thực phẩm & Đồ uống , Kế toán / Kiểm toán , Tài chính / Đầu tư',
 'Dịch vụ khách hàng, CNTT - Phần mềm, Tài chính / Đầu tư',
 'Hóa học',
 'CNTT - Phần mềm , Tài chính / Đầu tư , Kế toán / Kiểm toán',
 'CNTT - Phần mềm , Thương mại điện tử , CNTT - Phần cứng / Mạng',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Bưu chính viễn thông',
 'CNTT - Phần mềm , Bưu chính viễn thông , CNTT - Phần cứng / Mạng',
 'CNTT - Phần mềm , Giáo dục / Đào tạo',
 'CNTT - Phần cứng / Mạng , CNTT - Phần mềm , Mỹ thuật / Nghệ thuật / Thiết kế',
 'Bán hàng / Kinh doanh , Vận chuyển / Giao nhận /  Kho vận',
 'Thống kê , Sản xuất / Vận hành sản xuất , Dệt may / Da giày / Thời trang',
 'Tiếp thị / Marketing , Tiếp thị trực tuyến , Giáo dục / Đào tạo',
 'CNTT - Phần mềm , Cơ khí / Ô tô / Tự động hóa , CNTT - Phần cứng / Mạng',
 'Dịch vụ khách hàng , Bất động sản',
 'Bán hàng / Kinh doanh , CNTT - Phần mềm , Quản lý điều hành',
 'Hành chính / Thư ký , Bán hàng / Kinh doanh , Quản lý điều hành',
 'Tài chính / Đầu tư , Kế toán / Kiểm toán , Ngân hàng',
 'Bán hàng / Kinh doanh , Bán lẻ / Bán sỉ , Thực phẩm & Đồ uống',
 'Kế toán / Kiểm toán , CNTT - Phần mềm',
 'Bán hàng / Kinh doanh , Sản xuất / Vận hành sản xuất , Bán lẻ / Bán sỉ',
 'Hóa học , Công nghệ sinh học , Công nghệ thực phẩm / Dinh dưỡng',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Quản lý điều hành',
 'CNTT - Phần mềm , Bán Hàng Kỹ Thuật , Ngân hàng',
 'Chứng khoán , Tài chính / Đầu tư',
 'Bảo hiểm',
 'Quản lý chất lượng (QA/QC) , Sản xuất / Vận hành sản xuất',
 'CNTT - Phần mềm , Bất động sản',
 'Vận chuyển / Giao nhận /  Kho vận , Bán hàng / Kinh doanh',
 'Xuất nhập khẩu , Bán hàng / Kinh doanh , Hàng hải',
 'Ngân hàng , Bảo hiểm , Tài chính / Đầu tư',
 'Thương mại điện tử , Tiếp thị / Marketing , CNTT - Phần mềm',
 'Giáo dục / Đào tạo , Nhân sự , Nông nghiệp',
 'Sản xuất / Vận hành sản xuất , Quản lý chất lượng (QA/QC)',
 'Giáo dục / Đào tạo , Ngân hàng , CNTT - Phần mềm',
 'CNTT - Phần mềm, Sản xuất / Vận hành sản xuất, Đồ gỗ',
 'Tài chính / Đầu tư, Thống kê, Mới tốt nghiệp / Thực tập',
 'Kế toán / Kiểm toán, Tài chính / Đầu tư, Thống kê',
 'Tài chính / Đầu tư, Kế toán / Kiểm toán, Thống kê',
 'Bán hàng / Kinh doanh, Thực phẩm & Đồ uống, Bán lẻ / Bán sỉ',
 'CNTT - Phần mềm, Sản xuất / Vận hành sản xuất',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp, Cơ khí / Ô tô / Tự động hóa',
 'Thực phẩm & Đồ uống, Công nghệ sinh học, Công nghệ thực phẩm / Dinh dưỡng',
 'Môi trường, Phi chính phủ / Phi lợi nhuận',
 'Thực phẩm & Đồ uống, Vận chuyển / Giao nhận /  Kho vận, Sản xuất / Vận hành sản xuất',
 'Ngân hàng, CNTT - Phần mềm, Tài chính / Đầu tư',
 'CNTT - Phần mềm, CNTT - Phần cứng / Mạng, Sản xuất / Vận hành sản xuất',
 'Quản lý điều hành, CNTT - Phần mềm, Nhân sự',
 'Ngân hàng, CNTT - Phần mềm, CNTT - Phần cứng / Mạng',
 'Bán hàng / Kinh doanh, Ngân hàng, Dịch vụ khách hàng',
 'Tài chính / Đầu tư, Bán hàng / Kinh doanh, Ngân hàng',
 'Ngân hàng, Bán lẻ / Bán sỉ',
 'Kế toán / Kiểm toán, Quản lý chất lượng (QA/QC), Thống kê',
 'Nhân sự , Quản lý chất lượng (QA/QC)',
 'Bán lẻ / Bán sỉ , Hàng gia dụng / Chăm sóc cá nhân , Dược phẩm/ Hóa Mỹ Phẩm',
 'Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh , Xuất nhập khẩu',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Mỹ thuật / Nghệ thuật / Thiết kế',
 'Ngân hàng , Thống kê',
 'Tiếp thị / Marketing , Thương mại điện tử , Quảng cáo / Đối ngoại / Truyền Thông',
 'Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh , Thực phẩm & Đồ uống',
 'CNTT - Phần mềm , Mới tốt nghiệp / Thực tập , Ngành khác',
 'Dịch vụ khách hàng , Mới tốt nghiệp / Thực tập , CNTT - Phần mềm',
 'Dịch vụ khách hàng , Mới tốt nghiệp / Thực tập , Thương mại điện tử',
 'Cơ khí / Ô tô / Tự động hóa , Sản xuất / Vận hành sản xuất , Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'Cơ khí / Ô tô / Tự động hóa , Quản lý chất lượng (QA/QC) , Đồ gỗ',
 'Tiếp thị / Marketing , Tài chính / Đầu tư , Kế toán / Kiểm toán',
 'Tiếp thị / Marketing , Dịch vụ khách hàng , Ngân hàng',
 'Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh',
 'Thực phẩm & Đồ uống , Bán lẻ / Bán sỉ',
 'Dệt may / Da giày / Thời trang , Sản xuất / Vận hành sản xuất , Vận chuyển / Giao nhận /  Kho vận',
 'Thống kê , Thu mua / Vật tư',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , Cơ khí / Ô tô / Tự động hóa , Thu mua / Vật tư',
 'Kế toán / Kiểm toán , Bán lẻ / Bán sỉ , Thương mại điện tử',
 'Thực phẩm & Đồ uống , Công nghệ thực phẩm / Dinh dưỡng , Hóa học',
 'Tiếp thị / Marketing , Tiếp thị trực tuyến , Ngân hàng',
 'CNTT - Phần mềm , Tiếp thị / Marketing , Bán hàng / Kinh doanh',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , Sản xuất / Vận hành sản xuất , Quản lý chất lượng (QA/QC)',
 'Tài chính / Đầu tư , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Quản lý chất lượng (QA/QC) , Ngân hàng , Tài chính / Đầu tư',
 'Hành chính / Thư ký , Kế toán / Kiểm toán , Bán lẻ / Bán sỉ',
 'Ngân hàng , Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh',
 'Quản lý điều hành , Ngân hàng , CNTT - Phần cứng / Mạng',
 'Kế toán / Kiểm toán , Sản xuất / Vận hành sản xuất',
 'Ngân hàng , Bán hàng / Kinh doanh , Tài chính / Đầu tư',
 'Kế toán / Kiểm toán , Ngân hàng , Tài chính / Đầu tư',
 'CNTT - Phần mềm , Nhân sự , CNTT - Phần cứng / Mạng',
 'Bất động sản , Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh',
 'Bảo hiểm , Bất động sản , Bán hàng / Kinh doanh',
 'Bán hàng / Kinh doanh , Dược phẩm/ Hóa Mỹ Phẩm , Xuất nhập khẩu',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Tài chính / Đầu tư',
 'Sản xuất / Vận hành sản xuất , Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'Bán hàng / Kinh doanh , Thương mại điện tử , CNTT - Phần mềm',
 'CNTT - Phần mềm , Tài chính / Đầu tư , CNTT - Phần cứng / Mạng',
 'CNTT - Phần mềm , Bán hàng / Kinh doanh , CNTT - Phần cứng / Mạng',
 'Kiến trúc , Xây dựng',
 'CNTT - Phần mềm , Thống kê , CNTT - Phần cứng / Mạng',
 'Nhân sự , Hành chính / Thư ký , CNTT - Phần mềm',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Bảo hiểm',
 'Chứng khoán , Tài chính / Đầu tư , Ngân hàng',
 'CNTT - Phần cứng / Mạng , CNTT - Phần mềm',
 'CNTT - Phần mềm , Sản xuất / Vận hành sản xuất , Xuất nhập khẩu',
 'Nông nghiệp , Thực phẩm & Đồ uống , Chăn nuôi / Thú y',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , CNTT - Phần mềm , Cơ khí / Ô tô / Tự động hóa',
 'CNTT - Phần mềm , Kế toán / Kiểm toán , Ngân hàng',
 'Sản xuất / Vận hành sản xuất , Nội ngoại thất , Đồ gỗ',
 'Luật / Pháp lý , Kế toán / Kiểm toán , Ngân hàng',
 'Chứng khoán , Tài chính / Đầu tư , Bán hàng / Kinh doanh',
 'CNTT - Phần mềm , Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'CNTT - Phần mềm , Chứng khoán',
 'CNTT - Phần mềm , Thương mại điện tử',
 'Hành chính / Thư ký , Sản xuất / Vận hành sản xuất',
 'Nhân sự , Hành chính / Thư ký , Sản xuất / Vận hành sản xuất',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Kiến trúc',
 'Dịch vụ khách hàng',
 'Ngân hàng , CNTT - Phần cứng / Mạng , CNTT - Phần mềm',
 'Dịch vụ khách hàng , Tiếp thị / Marketing , CNTT - Phần mềm',
 'Hành chính / Thư ký',
 'Hàng gia dụng / Chăm sóc cá nhân , Thực phẩm & Đồ uống , Bán hàng / Kinh doanh',
 'Tiếp thị / Marketing , Bán hàng / Kinh doanh , Thực phẩm & Đồ uống',
 'Sản xuất / Vận hành sản xuất , Thống kê , Ngành khác',
 'Tiếp thị / Marketing , Quảng cáo / Đối ngoại / Truyền Thông',
 'Ngân hàng , CNTT - Phần cứng / Mạng , Quản lý chất lượng (QA/QC)',
 'Sản xuất / Vận hành sản xuất , CNTT - Phần cứng / Mạng , CNTT - Phần mềm',
 'Tiếp thị / Marketing , Bán hàng / Kinh doanh , Ngành khác',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Ngân hàng',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Bất động sản',
 'Tiếp thị / Marketing , Tài chính / Đầu tư',
 'Mới tốt nghiệp / Thực tập , Dịch vụ khách hàng , Hành chính / Thư ký',
 'Quản lý điều hành , Nhân sự , Quảng cáo / Đối ngoại / Truyền Thông',
 'Tài chính / Đầu tư , Kế toán / Kiểm toán , Chứng khoán',
 'Tiếp thị / Marketing , Ngành khác , Quảng cáo / Đối ngoại / Truyền Thông',
 'Hành chính / Thư ký , Ngân hàng',
 'Cơ khí / Ô tô / Tự động hóa , Ngân hàng , Tài chính / Đầu tư',
 'Du lịch , Quảng cáo / Đối ngoại / Truyền Thông',
 'CNTT - Phần cứng / Mạng , CNTT - Phần mềm , Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'Thực phẩm & Đồ uống , Công nghệ thực phẩm / Dinh dưỡng , Quản lý chất lượng (QA/QC)',
 'Ngân hàng , Kế toán / Kiểm toán , CNTT - Phần mềm',
 'Bán hàng / Kinh doanh , Bán lẻ / Bán sỉ , Mới tốt nghiệp / Thực tập',
 'Dược phẩm/ Hóa Mỹ Phẩm , Bán lẻ / Bán sỉ , Bán hàng / Kinh doanh',
 'Tài chính / Đầu tư , Kế toán / Kiểm toán',
 'CNTT - Phần mềm , Bán hàng / Kinh doanh , Bán lẻ / Bán sỉ',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Xuất nhập khẩu',
 'Dệt may / Da giày / Thời trang , Bán hàng / Kinh doanh , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Bán lẻ / Bán sỉ , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp , CNTT - Phần mềm',
 'Bán lẻ / Bán sỉ , Dược phẩm/ Hóa Mỹ Phẩm , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Mỹ thuật / Nghệ thuật / Thiết kế , CNTT - Phần mềm',
 'Cơ khí / Ô tô / Tự động hóa , Điện / Điện tử / Điện lạnh / Điện công nghiệp',
 'Luật / Pháp lý , CNTT - Phần mềm',
 'Thương mại điện tử , CNTT - Phần mềm , Tiếp thị trực tuyến',
 'Tiếp thị / Marketing , Dịch vụ khách hàng , Quảng cáo / Đối ngoại / Truyền Thông',
 'Thương mại điện tử , CNTT - Phần mềm , Ngành khác',
 'Thực phẩm & Đồ uống , Cơ khí / Ô tô / Tự động hóa , Bảo trì / Sửa chữa',
 'Hành chính / Thư ký , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Sản xuất / Vận hành sản xuất',
 'Tài chính / Đầu tư , Thống kê , Bán lẻ / Bán sỉ',
 'Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp , Thống kê , Tài chính / Đầu tư',
 'Ngân hàng , CNTT - Phần mềm , Bảo hiểm',
 'Ngân hàng, Tài chính / Đầu tư, Kế toán / Kiểm toán',
 'CNTT - Phần mềm , Bán lẻ / Bán sỉ',
 'Kế toán / Kiểm toán , Xây dựng , Sản xuất / Vận hành sản xuất',
 'Kế toán / Kiểm toán , CNTT - Phần mềm , Tư vấn',
 'Tài chính / Đầu tư , Kế toán / Kiểm toán , Thương mại điện tử',
 'Tiếp thị / Marketing , Thực phẩm & Đồ uống , Bán lẻ / Bán sỉ',
 'Bán hàng / Kinh doanh , Nhà hàng / Khách sạn , Bán lẻ / Bán sỉ',
 'CNTT - Phần mềm , Bất động sản , Tài chính / Đầu tư',
 'Vận chuyển / Giao nhận /  Kho vận , CNTT - Phần mềm',
 'Thương mại điện tử , Tiếp thị / Marketing , Tiếp thị trực tuyến',
 'Dược phẩm/ Hóa Mỹ Phẩm , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp , Thu mua / Vật tư',
 'Hàng gia dụng / Chăm sóc cá nhân , Thực phẩm & Đồ uống , Mới tốt nghiệp / Thực tập',
 'Kế toán / Kiểm toán , Cơ khí / Ô tô / Tự động hóa , Sản xuất / Vận hành sản xuất',
 'Tiếp thị / Marketing , Tiếp thị trực tuyến , Quảng cáo / Đối ngoại / Truyền Thông',
 'CNTT - Phần mềm , Ngân hàng , Mới tốt nghiệp / Thực tập',
 'CNTT - Phần mềm , Quản lý điều hành , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , Dịch vụ khách hàng',
 'Nhân sự , Bán lẻ / Bán sỉ',
 nan,
 'Thống kê , Sản xuất / Vận hành sản xuất',
 'Bảo hiểm , Chứng khoán , Tài chính / Đầu tư',
 'CNTT - Phần mềm , Thực phẩm & Đồ uống , Bán lẻ / Bán sỉ',
 'Tiếp thị / Marketing , Bán hàng / Kinh doanh , Thống kê',
 'Hành chính / Thư ký , Mới tốt nghiệp / Thực tập',
 'Bán lẻ / Bán sỉ , Tài chính / Đầu tư , Dệt may / Da giày / Thời trang',
 'CNTT - Phần mềm , Thương mại điện tử , Tiếp thị / Marketing',
 'Mới tốt nghiệp / Thực tập , Dịch vụ khách hàng , Biên phiên dịch',
 'CNTT - Phần mềm , Kế toán / Kiểm toán , Thống kê',
 'CNTT - Phần mềm , Tài chính / Đầu tư , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Sản xuất / Vận hành sản xuất , Thống kê , CNTT - Phần mềm',
 'CNTT - Phần mềm , Thực phẩm & Đồ uống , Công nghệ thực phẩm / Dinh dưỡng',
 'Tiếp thị / Marketing , CNTT - Phần mềm , Thống kê',
 'Hành chính / Thư ký , Quản lý điều hành , Bưu chính viễn thông',
 'Kế toán / Kiểm toán , Tài chính / Đầu tư , Sản xuất / Vận hành sản xuất',
 'Ngân hàng , Tài chính / Đầu tư , Luật / Pháp lý',
 'Sản xuất / Vận hành sản xuất , Thực phẩm & Đồ uống',
 'Ngân hàng , Thống kê , CNTT - Phần mềm',
 'Bán hàng / Kinh doanh , Dược phẩm/ Hóa Mỹ Phẩm , Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Y tế / Chăm sóc sức khỏe / Thẩm mỹ / Làm đẹp',
 'Nhân sự , Hành chính / Thư ký',
 'Nhân sự , Nhà hàng / Khách sạn , Hành chính / Thư ký',
 'Điện / Điện tử / Điện lạnh / Điện công nghiệp , CNTT - Phần cứng / Mạng , Sản xuất / Vận hành sản xuất',
 'CNTT - Phần mềm , Thống kê , Ngân hàng',
 'Giáo dục / Đào tạo , CNTT - Phần mềm , CNTT - Phần cứng / Mạng',
 'Nông nghiệp , Thực phẩm & Đồ uống',
 'Tiếp thị / Marketing , Thống kê , Ngành khác',
 'Dịch vụ khách hàng , Bất động sản , Tư vấn',
 'Dịch vụ khách hàng , Bán Hàng Kỹ Thuật , Tài chính / Đầu tư',
 'Bán hàng / Kinh doanh , Dịch vụ khách hàng , CNTT - Phần mềm',
 'Tiếp thị trực tuyến , Tiếp thị / Marketing , Thương mại điện tử',
 'CNTT - Phần mềm , Bưu chính viễn thông',
 'Kế toán / Kiểm toán , Bán lẻ / Bán sỉ , Thực phẩm & Đồ uống',
 'Giáo dục / Đào tạo , Nhân sự',
 'CNTT - Phần mềm , Xây dựng , Ngành khác',
 'Dệt may / Da giày / Thời trang , Bán lẻ / Bán sỉ',
 'Vận chuyển / Giao nhận /  Kho vận , Bán lẻ / Bán sỉ , Sản xuất / Vận hành sản xuất',
 'Cơ khí / Ô tô / Tự động hóa , Điện / Điện tử / Điện lạnh / Điện công nghiệp , Mỹ thuật / Nghệ thuật / Thiết kế',
 'CNTT - Phần mềm , Công nghệ sinh học , Tài chính / Đầu tư',
 'Tiếp thị / Marketing , Tài chính / Đầu tư , Quản lý điều hành',
 'Bán lẻ / Bán sỉ',
 'Kế toán / Kiểm toán , CNTT - Phần mềm , Tài chính / Đầu tư',
 'Bảo hiểm , CNTT - Phần cứng / Mạng',
 'Dịch vụ khách hàng , CNTT - Phần mềm , Bảo trì / Sửa chữa',
 'CNTT - Phần mềm , CNTT - Phần cứng / Mạng , Thống kê',

In [18]:
# Cột level_employee cấp bậc nhân viên có bao nhiêu giá trị duy nhất
df['level_employee'].unique().tolist()

['Nhân viên',
 'Mới tốt nghiệp',
 'Trưởng nhóm / Giám sát',
 'Quản lý',
 'Sinh viên/ Thực tập sinh',
 'Giám đốc',
 'Phó Giám đốc',
 nan]

In [17]:
# Cột experience năm kinh nghiệm có bao nhiêu giá trị duy nhất
df['experience'].unique().tolist()

['3 - 5 Năm',
 'Trên 5 Năm',
 'Trên 3 Năm',
 'Trên 1 Năm',
 nan,
 '5 - 7 Năm',
 '2 - 5 Năm',
 '2 - 3 Năm',
 'Chưa có kinh nghiệm',
 '3 - 4 Năm',
 '1 - 3 Năm',
 'Trên 2 Năm',
 '1 - 8 Năm',
 '2 - 4 Năm',
 '1 - 2 Năm',
 '7 - 30 Năm',
 'Trên 7 Năm',
 '4 - 6 Năm',
 '4 - 5 Năm',
 '1 - 5 Năm',
 '2 - 7 Năm',
 '5 - 10 Năm',
 '5 - 15 Năm',
 '4 - 7 Năm',
 '7 - 20 Năm',
 '3 - 10 Năm',
 '4 - 10 Năm',
 'Trên 4 Năm',
 '5 - 8 Năm',
 '10 - 12 Năm',
 'Lên đến 2 Năm',
 'Lên đến 5 Năm',
 '6 - 8 Năm',
 'null - null Năm',
 '3 - 15 Năm',
 '7 - 10 Năm',
 '5 - 6 Năm',
 '4 - 8 Năm',
 'Lên đến 3 Năm',
 '1 - 10 Năm',
 'Không yêu cầu kinh nghiệm',
 '2 - 10 Năm',
 '10 Năm',
 '7 Năm',
 '1 Năm',
 '3 - 7 Năm',
 'Trên 8 Năm',
 'Lên đến 1 Năm',
 '6 - 15 Năm',
 '3 Năm',
 '10 - 20 Năm',
 '3 - 14 Năm',
 'Trên 6 Năm',
 '8 - 10 Năm',
 '1 - 4 Năm',
 '10 - 15 Năm',
 'Trên 10 Năm',
 '4 - 15 Năm',
 '9 - 10 Năm',
 '3 - 6 Năm',
 '7 - 15 Năm',
 '3 - 8 Năm',
 '1 - 7 Năm',
 '2 - 6 Năm']

In [4]:
# Cột education_level trình độ học vấn có bao nhiêu giá trị duy nhất
df['education_level'].unique().tolist()

['Đại học', nan, 'Cao đẳng', 'Trung cấp', 'Không yêu cầu bằng cấp']

In [1]:
# Cột hire_number số lượng tuyển dụng có bao nhiêu giá trị duy nhất
df['hire_number'].unique().tolist()

NameError: name 'df' is not defined

In [16]:
# Cột job_expertise chuyên môn công việc có bao nhiêu giá trị duy nhất
df['job_expertise'].unique().tolist()

['Phân tích dữ liệu, Nhân sự',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Chăm sóc sức khỏe / Làm đẹp, Y tế / Dược phẩm',
 'Data Analyst',
 'Data Analyst, Tài chính',
 'Kế toán tài chính, Tài chính, Kế toán, Kiểm toán',
 'Data Analyst, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, Logistic / Vận tải, IT - Phần mềm',
 'Data Analyst, IT - Phần mềm',
 'Data Analyst, Tài chính, IT - Phần mềm, An ninh mạng',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Kế toán',
 'Business Intelligence, Marketing / Quảng cáo, Kế toán, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Analyst, Thương mại điện tử, Marketing / Quảng cáo',
 'Data Analyst, Viễn thông, Nhân sự',
 'Phân tích dữ liệu, Năng lượng / Môi trường',
 'Business Analyst (Phân tích nghiệp vụ), Tài chính, Ngân hàng, Chứng khoán',
 'Data Analyst, IT - Phần mềm, Ngân hàng',
 'Data Analyst, Logistic / Vận tải, IT - Phần mềm',
 'Data Analyst, Game',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử',
 'Data Analyst, IT - Phần mềm, Điện toán đám mây (Cloud), IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Logistic / Vận tải',
 'Phân tích dữ liệu',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Y tế / Dược phẩm',
 'Phân tích dữ liệu, Năng lượng / Môi trường, Tổ chức phi lợi nhuận',
 'Data Analyst, Công nghệ kỹ thuật, IT - Phần mềm, Game',
 'Tư vấn nhân sự',
 'Data Analyst, IT - Phần mềm, May mặc / Thời trang, Logistic / Vận tải',
 'Data Analyst, Logistic / Vận tải',
 'Phân tích dữ liệu, An ninh mạng, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Logistic / Vận tải, Thương mại điện tử',
 'Data Analyst, IT - Phần mềm, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Tài chính',
 'Nghiên cứu thị trường (Market Research), Nhân sự, IT - Phần mềm, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Phân tích dữ liệu, Tài chính',
 'Data Analyst, Phát thanh / Truyền hình',
 'Data Analyst, Bất động sản, Thương mại điện tử, IT - Phần mềm',
 'Thu hồi nợ, Tài chính, Ngân hàng',
 'Data Analyst, Ngân hàng',
 'Phân tích dữ liệu, Kiểm toán, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Ngân hàng, Tài chính, Bảo hiểm',
 'Phân tích dữ liệu, Thương mại điện tử, Logistic / Vận tải',
 'Phân tích dữ liệu, Chính phủ/Dịch vụ công',
 'Quản lý cơ sở vật chất',
 'Data Analyst, IT - Phần mềm, Kế toán, Tài chính',
 'Data Scientist, Chứng khoán, IT - Phần mềm',
 'Data Analyst, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần mềm',
 'Data Engineer',
 'Phân tích dữ liệu, Năng lượng / Môi trường, Xây dựng',
 'Business Analyst (Phân tích nghiệp vụ)',
 'Kinh doanh phần mềm, B2C',
 'Data Engineer, IT - Phần mềm, Ngân hàng',
 'Data Analyst, IT - Phần cứng và máy tính, Chính phủ/Dịch vụ công, In ấn / Xuất bản',
 'Business Intelligence, Marketing / Quảng cáo, Quan hệ công chúng',
 'Business Intelligence',
 'Business Intelligence, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Business Intelligence, Marketing / Quảng cáo, Game, Ngân hàng',
 'Business Intelligence, Ngân hàng, Tài chính, Bảo hiểm',
 'Business Intelligence, IT - Phần mềm',
 'Business Intelligence, Marketing / Quảng cáo',
 'Business Intelligence, IT - Phần mềm, Thương mại điện tử, Ngân hàng',
 'Data Labeling (Gán nhãn dữ liệu)',
 'Backend Developer, IT - Phần mềm',
 'Software Engineer',
 'Data Analyst, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần mềm',
 'Business Analyst (Phân tích nghiệp vụ), IT - Phần mềm, Ngân hàng',
 'Business Analyst (Phân tích nghiệp vụ), IT - Phần mềm',
 'Phân tích dữ liệu, Chính phủ/Dịch vụ công, Báo chí, Tài chính',
 'Data Analyst, Logistic / Vận tải, Kho vận',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Sản xuất',
 'Data Analyst, Nhân sự',
 'Phân tích dữ liệu, Giáo dục / Đào tạo',
 'Business Intelligence, Tài chính',
 'Business Intelligence, Kế toán, Logistic / Vận tải',
 'Business Intelligence, Chăm sóc sức khỏe / Làm đẹp, Giáo dục / Đào tạo, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Thương mại điện tử, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Du lịch, Marketing / Quảng cáo, IT - Phần mềm',
 'Business Intelligence, Marketing / Quảng cáo, Du lịch',
 'Business Intelligence, Thương mại điện tử, Logistic / Vận tải, Kho vận',
 'Product Analyst/Research, Viễn thông, IT - Phần mềm',
 'Product Analyst/Research, Giáo dục / Đào tạo, Marketing / Quảng cáo, Thương mại điện tử',
 'Chuyên môn khác, IT - Phần mềm',
 'Kiểm soát và báo cáo tài chính, Tài chính, Ngân hàng',
 'Product Analyst/Research, Game, Marketing / Quảng cáo',
 'Product Analyst/Research',
 'Data Engineer, IT - Phần mềm, Ngân hàng, Tài chính',
 'Data Engineer, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Sản xuất, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Thương mại điện tử',
 'Data Engineer, IT - Phần mềm, Tài chính, Ngân hàng',
 'Data Engineer, Điện toán đám mây (Cloud)',
 'Data Engineer, Tài chính, Ngân hàng, IT - Phần mềm',
 'Data Engineer, Ngân hàng, Tài chính, Điện toán đám mây (Cloud)',
 'Data Engineer, An ninh mạng, Công nghệ kỹ thuật',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Ngân hàng',
 'Data Engineer, IT - Phần cứng và máy tính',
 'Data Scientist, Game',
 'Data Scientist',
 'Data Scientist, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm, Chứng khoán',
 'Công nhân vận hành máy, Lao động phổ thông',
 'Chuyên môn Điện/Điện tử/Viễn thông khác',
 'AI Engineer, IT - Phần mềm, Viễn thông, Bưu chính',
 'AI Engineer, Xây dựng, Thiết kế / Kiến trúc, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, An ninh mạng',
 'AI Engineer, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Kỹ thuật điện/điện tử, Điện / Điện tử / Điện lạnh',
 'Bán hàng kỹ thuật IT, B2B, B2C, B2G',
 'AI Engineer, IT - Phần mềm, Điện / Điện tử / Điện lạnh, Công nghệ kỹ thuật',
 'AI Engineer',
 'AI Engineer, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'AI Engineer, IT - Phần mềm, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG',
 'AI Engineer, IT - Phần mềm, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, An ninh mạng',
 'Digital Marketing, Marketing / Quảng cáo',
 'Animation Design, Marketing / Quảng cáo, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Animation Design, Mỹ thuật / Nghệ thuật / Điện ảnh, Marketing / Quảng cáo',
 'Trợ lý/Thư ký, Thiết kế / Kiến trúc',
 'AI Engineer, IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG, IT - Phần cứng và máy tính',
 'Tích hợp hệ thống, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'Kỹ sư phân tích yêu cầu, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Sales IT Phần mềm khác, IT - Phần mềm, Viễn thông, B2B',
 'AI Engineer, IT - Phần mềm, Y tế / Dược phẩm',
 'IT Project Manager, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Thương mại điện tử',
 'Content Marketing, Giáo dục / Đào tạo, Marketing / Quảng cáo, Báo chí',
 'Chuyên môn Công nghệ thông tin khác',
 'AI Engineer, IT - Phần mềm, Tài chính, Ngân hàng',
 'Hoạch định tài chính, Tài chính, Bất động sản, Ngân hàng',
 'Chuyên môn khác, Công nghệ kỹ thuật, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Sales Kỹ thuật khác, Xây dựng, B2B, Direct Sales',
 'AI Engineer, Viễn thông, Công nghệ kỹ thuật',
 'Chuyên môn Phim và truyền hình/Báo chí/Xuất bản khác, Mỹ thuật / Nghệ thuật / Điện ảnh',
 'Social Content, Marketing / Quảng cáo',
 'AI Engineer, Hàng không',
 'Vận hành sàn thương mại điện tử, Thương mại điện tử',
 'AI Engineer, Thương mại điện tử',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Game',
 'Chuyên môn Điện tử/Phần cứng khác',
 'Social Media, Marketing / Quảng cáo, Bất động sản',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Digital Marketing',
 'AI Engineer, Giáo dục / Đào tạo, Công nghệ kỹ thuật',
 'AI Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Công nghệ kỹ thuật',
 'Photographer/Video Editor',
 'Kỹ thuật IT, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Chuyên môn Quảng cáo/Sáng tạo khác, Giáo dục / Đào tạo, Marketing / Quảng cáo, IT - Phần mềm',
 'Digital Marketing, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Giáo viên Tin học',
 'System Engineer',
 'Tích hợp hệ thống, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Kỹ sư tự động hóa, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'AI Engineer, IT - Phần mềm, Game',
 'AI Engineer, IT - Phần mềm, Game, Điện toán đám mây (Cloud)',
 'Database Administrator (DBA)',
 'System Administrator, IT - Phần cứng và máy tính',
 'Database Administrator (DBA), Tài chính, Ngân hàng, IT - Phần mềm',
 'Database Administrator (DBA), Kế toán',
 'Database Administrator (DBA), IT - Phần mềm',
 'Database Administrator (DBA), IT - Phần mềm, Sản xuất, IT - Phần cứng và máy tính',
 'Database Administrator (DBA), IT - Phần cứng và máy tính',
 'Data Analyst, IT - Phần mềm, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần mềm, Ngân hàng, Tài chính',
 'Data Analyst, Tài chính, Ngân hàng',
 'Product Analyst/Research, Nhân sự, Thương mại điện tử',
 'AI Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Viễn thông',
 'AI Engineer, IT - Phần mềm, Ngân hàng',
 'IT Project Manager',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Công nghệ kỹ thuật',
 'Software Engineer, IT - Phần mềm',
 'Database Administrator (DBA), Tài chính, Ngân hàng',
 'Data Scientist, Ngân hàng, Tài chính, IT - Phần mềm',
 'Data Analyst, Sản xuất',
 'Phân tích dữ liệu, Y tế / Dược phẩm',
 'Mã hóa và bảo mật dữ liệu, Game',
 'Chuyên môn khác, Thương mại điện tử',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Điện / Điện tử / Điện lạnh',
 'Phân tích dữ liệu, Tài chính, Kế toán, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, IT - Phần mềm, Viễn thông, Nhân sự',
 'Business Intelligence, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Database Administrator (DBA), IT - Phần mềm, Viễn thông',
 'Data Engineer, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Game',
 'Phân tích dữ liệu, IT - Phần mềm',
 'Chuyên môn Marketing, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Kho vận, Y tế / Dược phẩm',
 'Product Analyst/Research, Thương mại điện tử',
 'Data Engineer, IT - Phần mềm, Thương mại điện tử',
 'Data Scientist, An ninh mạng, Ngân hàng, IT - Phần mềm',
 'AI Engineer, Game',
 'Thiết kế đồ họa (Graphic Design), Thiết kế / Kiến trúc',
 'Photographer/Video Editor, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'AI Engineer, IT - Phần mềm, Ngân hàng, Tài chính',
 'Sales IT Phần mềm khác, IT - Phần mềm, Viễn thông, B2B, Direct Sales',
 'Database Administrator (DBA), IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Analyst, Viễn thông',
 'Data Analyst, IT - Phần mềm, Game, Marketing / Quảng cáo',
 'Business Intelligence, Tài chính, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Data Analyst, Thương mại điện tử, Logistic / Vận tải, Nhân sự',
 'Chuyên môn Market Research and Analysis khác, Marketing / Quảng cáo, Ngân hàng, Hàng không',
 'Business Analyst (Phân tích nghiệp vụ), Logistic / Vận tải, Thương mại điện tử',
 'Data Analyst, Thương mại điện tử, IT - Phần mềm',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Thương mại điện tử',
 'Phân tích dữ liệu, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, May mặc / Thời trang, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Product Analyst/Research, IT - Phần mềm, IT - Phần cứng và máy tính, Giáo dục / Đào tạo',
 'Data Engineer, IT - Phần mềm, An ninh mạng, Điện toán đám mây (Cloud)',
 'Data Engineer, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Data Engineer, IT - Phần mềm, Y tế / Dược phẩm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'QA Engineer',
 'Data Scientist, IT - Phần mềm, Thương mại điện tử',
 'Data Scientist, Tài chính, Ngân hàng, IT - Phần mềm',
 'Data Scientist, IT - Phần mềm, IT - Phần cứng và máy tính, Năng lượng / Môi trường',
 'AI Engineer, IT - Phần mềm, Công nghệ kỹ thuật, IT - Phần cứng và máy tính',
 'AI Engineer, IT - Phần mềm, Marketing / Quảng cáo',
 'Concept Artist, Phát thanh / Truyền hình',
 'Data Analyst, Game, IT - Phần mềm',
 'Data Analyst, Giáo dục / Đào tạo',
 'Phân tích dữ liệu, Ngân hàng, Tài chính, Kế toán',
 'Chuyên môn khác, Tài chính, Chứng khoán, Kế toán',
 'Phân tích dữ liệu, Công nghệ kỹ thuật, Hàng hải',
 'Business Intelligence, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'Data Scientist, Tài chính, Công nghệ kỹ thuật, Năng lượng / Môi trường',
 'Data Scientist, Năng lượng / Môi trường, Tài chính, Công nghệ kỹ thuật',
 'Giáo viên bộ môn khác, IT - Phần mềm, Cơ khí / Tự động hóa, Công nghệ kỹ thuật',
 'Chuyên môn khác, Bảo hiểm, Tài chính',
 'Quản lý dự án kỹ thuật, IT - Phần mềm, Thương mại điện tử',
 'Phân tích dữ liệu, Tài chính, Ngân hàng',
 'Data Analyst, IT - Phần mềm, Thương mại điện tử, Marketing / Quảng cáo',
 'Data Analyst, IT - Phần mềm, Tài chính, Sản xuất',
 'Data Analyst, IT - Phần mềm, Bảo hiểm, Tài chính',
 'Business Intelligence, Tài chính, Chứng khoán',
 'Data Engineer, Năng lượng / Môi trường, Công nghệ kỹ thuật, IT - Phần mềm',
 'Data Engineer, Điện toán đám mây (Cloud), Thương mại điện tử, IT - Phần mềm',
 'Data Engineer, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Engineer, Thương mại điện tử, Nhà hàng / Khách sạn',
 'Trợ lý/Thư ký, Ngân hàng',
 'Software Tester (Automation & Manual), IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Viễn thông, Tài chính',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Viễn thông',
 'AI Researcher, Tài chính, Bảo hiểm',
 'Chuyên môn khác',
 'AI Engineer, Marketing / Quảng cáo, Công nghệ kỹ thuật',
 'AI Researcher',
 'Kinh doanh phần mềm, B2B',
 'Data Analyst, Quan hệ công chúng, Marketing / Quảng cáo, Chăm sóc sức khỏe / Làm đẹp',
 'Phân tích dữ liệu, Logistic / Vận tải, Kho vận',
 'Phân tích dữ liệu, Viễn thông',
 'Phân tích dữ liệu, Thực phẩm / Đồ uống, Y tế / Dược phẩm',
 'Data Analyst, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'Data Analyst, Bán lẻ - Hàng tiêu dùng - FMCG, Thực phẩm / Đồ uống, Thương mại điện tử',
 'Chuyên môn khác, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, Giáo dục / Đào tạo, IT - Phần mềm',
 'Phóng viên/Biên tập viên tin tức',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG, May mặc / Thời trang',
 'GIS Engineer, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Điện toán đám mây (Cloud), Công nghệ kỹ thuật',
 'Chuyên môn khác, Chứng khoán, Tài chính',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính, Điện toán đám mây (Cloud)',
 'AI Engineer, Bất động sản, IT - Phần mềm',
 'Fullstack Developer, IT - Phần mềm',
 'AI Engineer, Tài chính, Logistic / Vận tải, Bảo hiểm',
 'Chuyên môn Marketing/PR/Quảng cáo khác, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Content Marketing, Marketing / Quảng cáo, Thực phẩm / Đồ uống',
 'Biên kịch, Phát thanh / Truyền hình, Marketing / Quảng cáo, Chăm sóc sức khỏe / Làm đẹp',
 'Vận hành chung',
 'Product Owner/Product Manager, IT - Phần mềm, IT - Phần cứng và máy tính, Điện toán đám mây (Cloud)',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm, Thương mại điện tử',
 'Business Intelligence, Ngân hàng',
 'AI Engineer, IT - Phần mềm, May mặc / Thời trang',
 'Data Analyst, IT - Phần mềm, Tài chính, Ngân hàng',
 'Phân tích dữ liệu, Bất động sản, Tài chính',
 'Business Intelligence, Logistic / Vận tải, Thương mại điện tử',
 'Thiết kế đồ họa (Graphic Design), Thương mại điện tử, Marketing / Quảng cáo, Thiết kế / Kiến trúc',
 'AI Engineer, IT - Phần mềm, Ngân hàng, Bảo hiểm',
 'Phân tích dữ liệu, Tài chính, IT - Phần mềm',
 'Phân tích dữ liệu, IT - Phần mềm, Viễn thông, Bưu chính',
 'Phân tích dữ liệu, Thương mại điện tử',
 'Product Analyst/Research, IT - Phần mềm',
 'Data Engineer, IT - Phần mềm, Viễn thông, Ngân hàng',
 'Data Engineer, IT - Phần cứng và máy tính, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Data Analyst, IT - Phần mềm, Y tế / Dược phẩm',
 'Phân tích dữ liệu, Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Tài chính',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Business Intelligence, Y tế / Dược phẩm',
 'Data Scientist, IT - Phần mềm, Y tế / Dược phẩm',
 'Business Analyst (Phân tích nghiệp vụ), Thương mại điện tử, Bán lẻ - Hàng tiêu dùng - FMCG, Marketing / Quảng cáo',
 'AI Engineer, IT - Phần mềm, Y tế / Dược phẩm, An ninh mạng',
 'AI Engineer, IT - Phần cứng và máy tính, An ninh mạng, Chứng khoán',
 'DevOps Engineer, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Tài chính, Chứng khoán',
 'Chief Technology Officer (CTO), An ninh mạng, IT - Phần cứng và máy tính',
 'Tư vấn CNTT/IT consultant, IT - Phần mềm, Công nghệ kỹ thuật, Điện toán đám mây (Cloud)',
 'Kinh doanh phần mềm, IT - Phần mềm, Marketing / Quảng cáo, B2B, B2C, Direct Sales, Telesales, Online Sales',
 'AI Engineer, An ninh mạng, IT - Phần mềm, IT - Phần cứng và máy tính',
 'AI Engineer, IT - Phần mềm, Viễn thông',
 'Database Administrator (DBA), IT - Phần mềm, Điện toán đám mây (Cloud), IT - Phần cứng và máy tính',
 'Data Analyst, IT - Phần cứng và máy tính, IT - Phần mềm, Sản xuất',
 'Data Analyst, Marketing / Quảng cáo, Du lịch',
 'Chuyên môn Nhân sự/Hành chính/Pháp chế khác, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Phân tích dữ liệu, Tài chính, Ngân hàng, Chứng khoán',
 'Phân tích dữ liệu, Sản xuất, Kế toán, May mặc / Thời trang',
 'Business Intelligence, Bán lẻ - Hàng tiêu dùng - FMCG, May mặc / Thời trang, Marketing / Quảng cáo',
 'Product Analyst/Research, IT - Phần mềm, Marketing / Quảng cáo',
 'Product Analyst/Research, IT - Phần mềm, Điện toán đám mây (Cloud), An ninh mạng',
 'AI Engineer, Y tế / Dược phẩm, Marketing / Quảng cáo',
 'AI Engineer, An ninh mạng, IT - Phần cứng và máy tính, IT - Phần mềm',
 'AI Engineer, IT - Phần mềm, Logistic / Vận tải',
 'Technical Director, IT - Phần mềm',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Chuyên môn Công nghệ thông tin khác, IT - Phần mềm',
 'Data Analyst, Ngân hàng, Tài chính',
 'Data Analyst, Chính phủ/Dịch vụ công, IT - Phần mềm',
 'Phân tích dữ liệu, Bán lẻ - Hàng tiêu dùng - FMCG, Kế toán, May mặc / Thời trang',
 'Data Analyst, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Phân tích dữ liệu, Sản xuất, Bất động sản',
 'Phân tích dữ liệu, Thực phẩm / Đồ uống, Kiểm toán',
 'Business Intelligence, Thực phẩm / Đồ uống',
 'Data Engineer, IT - Phần mềm, Chính phủ/Dịch vụ công',
 'Data Engineer, IT - Phần cứng và máy tính, An ninh mạng',
 'Data Scientist, IT - Phần mềm, Điện toán đám mây (Cloud)',
 'Quản trị rủi ro, Ngân hàng, Tài chính',
 'Data Analyst, Tài chính, IT - Phần mềm',
 'Phân tích dữ liệu, Điện / Điện tử / Điện lạnh',
 'Data Engineer, Thương mại điện tử',
 'Data Scientist, Điện toán đám mây (Cloud), IT - Phần mềm, Bán lẻ - Hàng tiêu dùng - FMCG',
 'Kinh doanh phần mềm, Tài chính, Ngân hàng, Kế toán, B2B',
 'AI Engineer, IT - Phần mềm, IT - Phần cứng và máy tính',
 'Software Engineer, IT - Phần mềm, Cơ khí / Tự động hóa',
 'Content Creator, Chăm sóc sức khỏe / Làm đẹp, Y tế / Dược phẩm',